### ISSUE TITLE
Add links to AGOL authoritative services

### ISSUE THREAD

**Issue by stdavis** [agrc/gis.utah.gov#1004]
Thanks to the hard work of @MichaelAGRC and others, our AGOL services have become first-class. We should make sure that we have links to all of our authoritative services from their associated data pages and SGID Index on our website. There also may be other AGOL orgs whos services we should link to.

Here's a [list of all AGOL items that have the `sgid` tag and are marked as `authoritative`](https://utah.maps.arcgis.com/home/content.html?view=table&start=1&sortOrder=desc&sortField=modified&tags=sgid&contentstatus=org_authoritative&showFilters=true#content):

- [x] [UtahOilGasWells](http://utah.maps.arcgis.com/home/item.html?id=3bd7bcadd68140b3805e3621d9514294) (prioritized since Don Stayley asked for it)
- [ ] ~~[Municipalities_Modifications](https://utah.maps.arcgis.com/home/item.html?id=572efbac3c8b4799bf729cbeac36dc11)~~ - no match found on website
- [x] [SkiAreaLocations](https://utah.maps.arcgis.com/home/item.html?id=24029712a33f47feacc7b3f2ef75f179)
- [x] [StateFuelSites](https://utah.maps.arcgis.com/home/item.html?id=bbad0291cb754be48ae91dc7d82f6f5c)
- [x] [Utah PLSS Sections GCDB](https://utah.maps.arcgis.com/home/item.html?id=471c7281c52849b2860d36135e751c83)
- [x] [Utah PLSS Townships GCDB](https://utah.maps.arcgis.com/home/item.html?id=5f801b03df2644dd99dcbaa5840bf12d)
- [x] [Utah PLSS Quarter Quarter Sections_GCDB](https://utah.maps.arcgis.com/home/item.html?id=f3454ae613034039b63830c78105bec8)
- [x] [Utah PLSS Quarter Sections_GCDB](https://utah.maps.arcgis.com/home/item.html?id=58b655046e2f4a258dbbf6a6aeaa7b23)
- [x] [Utah Public Safety Answering Point (PSAP 911) Boundaries](https://utah.maps.arcgis.com/home/item.html?id=34f4c65991ce4d4299d3957efa35bf41)
- [x] [Utah Public Safety Answering Point (PSAP_911) Locations](https://utah.maps.arcgis.com/home/item.html?id=6c102c8fc5af413187db0910053d5ed8)
- [x] [UtahAddressPoints](https://utah.maps.arcgis.com/home/item.html?id=3f4f7a8efcd147febeca8bacaea67a14)
- [x] [UtahCountyBoundaries](https://utah.maps.arcgis.com/home/item.html?id=90431cac2f9f49f4bcf1505419583753)
- [x] [UtahLiquorStores](https://utah.maps.arcgis.com/home/item.html?id=61b7f10c194b4ec69d02e169db1da09a)
- [x] [UtahMunicipalBoundaries](https://utah.maps.arcgis.com/home/item.html?id=543fa1f073714198a3dbf8a292bdf30c)
- [x] [UtahPLSSGCDBPoints](https://utah.maps.arcgis.com/home/item.html?id=ef75c3c063ac4b9b996b70e21ce248fe)
- [x] [UtahRailroads](https://utah.maps.arcgis.com/home/item.html?id=fe20e5c6bb4240919d0cd5ba4116d106)
- [x] [UtahRoads](https://utah.maps.arcgis.com/home/item.html?id=478fbef62481427f95a3510a4707b24a)
- [x] [UtahSchools](https://utah.maps.arcgis.com/home/item.html?id=9e700ba2de90451d9c16c176d58e0b68)
- [x] [UtahZipCodeAreas](https://utah.maps.arcgis.com/home/item.html?id=4f9d1d1301864f8cabef08cbae7b2d3c)
- [ ] ~~[CityTownsLocations](https://utah.maps.arcgis.com/home/item.html?id=62a6b78d53a943db906de0abd1c9174f)~~ - no data page on website
- [x] [UtahGNISPlaceNames](https://utah.maps.arcgis.com/home/item.html?id=153301fffc8a4128884833e2f7ee1d6e)
- [x] [UtahParksLocal](https://utah.maps.arcgis.com/home/item.html?id=818536733987486b8082e4c5dec0a1dd)
- [x] [UtahSchoolDistrictBoundaries](https://utah.maps.arcgis.com/home/item.html?id=3e69ecf5c46a492aa9974f6fa03d1378)
- [x] [UtahOilGasFields](https://utah.maps.arcgis.com/home/item.html?id=7788ca033769450185e426686fcc0e09)

@MichaelAGRC Are there any others that should be linked to from our website?

**Comment by stdavis** [comment]
I updated/added all of these links in/to the [SGID Stewardship spreadsheet](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1). @steveoh How is this data propagated into the [SGID Index page](https://gis.utah.gov/data/sgid-index/)?

Also, what's the best way to get these AGOL links added to the data pages? I remember that we started to look at what the standard would be but I don't remember a final decision.

**Comment by steveoh** [comment]
I have a terminal command I run to update the sgid-index. But for future reference, it's the [datatable python script](https://github.com/agrc/gis.utah.gov/blob/master/scripts/datatable.py)

**Comment by stdavis** [comment]
@MichaelAGRC I've added links to AGOL items for everything that I could find matches for in our website. Would you mind submitting PRs for any new layers that you add or at least letting me know so that I can add them? This will be a great use case for webhooks in AGOL once they come out.
