### ISSUE TITLE
improve search page

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#1036]
The search page for the website only searches posts because of the implementation spawned from the github pages restrictions which no longer apply. 

We should consider using a more full featured search instead of what we are currently doing.

Options...

- [lunr.js](https://lunrjs.com/)
- [algolia](https://blog.algolia.com/instant-search-blog-documentation-jekyll-plugin/)

Things to note

- https://github.com/nextapps-de/flexsearch

**Comment by stdavis** [comment]
Can this issue be closed?
