### ISSUE TITLE
Utah Lake Trail Plan data

### ISSUE THREAD

**Issue by todrobbins** [agrc/gis.utah.gov#1063]
## Issue description
Looking for the shapefiles that drive this map: http://utahlakecommission.org/utah-lake-trail-plan/

Also, I'm wondering how up-to-date this map is since I live right by parcel ID 130740014 and know that segment of the proposed trail is already complete.

Anyhow, I know this is the general website repo, so maybe there's a better place to raise this issue. 🤣

**Comment by steveoh** [comment]
I don't think we have anything to do with that map or its data. This is our [trails data](https://gis.utah.gov/data/recreation/trails/). @brigsz or @gregbunce do you know anything about the commission?

**Comment by gregbunce** [comment]
Yeah, I don't think we do either.  At least I'm unaware of it.

**Comment by steveoh** [comment]
http://mountainland.org/img/mapping/gisdownload/UtahLakeTrail.zip

**Comment by todrobbins** [comment]
Thanks all! I'll follow up on those leads.
