### ISSUE TITLE
USGS Topo maps no longer available?

### ISSUE THREAD

**Issue by mtnmers** [agrc/gis.utah.gov#1065]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having
I used to be able to load the USGS scanned quad maps via the AGRC weblink in GIS.  They appear to no longer be available.  We use these regularly as USGS quad backgrounds are required for all U.S. Army Corps of Engineers permitting map submittals and would appreciate server access for ease of use.

#### What page is the problem visible

![image](https://user-images.githubusercontent.com/49410757/55744090-461ff280-59f1-11e9-95cc-e9b586c686e9.png)

#### Expected result
I expected:
Usually I can access the USGS maps no problem

#### Actual result
Instead:
Last week they just did not appear to be in the scanned maps folder, not the folder isn't even there.  Can you help me figure out if there is a new linked location for those maps through the web server rather than having to download entire tiles or counties manually as needed through your website?  Thanks!

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
I apologize that you weren't notified of this change. We tried very hard to let everyone know through the public channels we have access to. Please follow our [website](https://gis.utah.gov), [twitter](https://twitter.com/maputah), or sign up for our [newsletter](https://utah.us2.list-manage.com/subscribe/post?u=0f7773ca3c6d02d1c38851ee9&id=1fe9862f44) to be kept current with changes to AGRC services.

We temporarily turned off those services Saturday, January 5, through Thursday, January 10.

Here is the [image service deprecation article](https://gis.utah.gov/image-service-deprecation/). 

Here is the [article](https://gis.utah.gov/arc-gis-server-10-6-upgrade/) where we expressed intent and work arounds.

Here is the [newsletter](https://mailchi.mp/1b78ed5327fb/latest-updates-from-the-utah-agrc) with a link to the article
