### ISSUE TITLE
Best way to view IMG data files on macOS?

### ISSUE THREAD

**Issue by todrobbins** [agrc/gis.utah.gov#1102]
Looking for a good workflow to view IMG data files and didn't have much luck Googling except to find [SimpleDEMViewer]() for macOS and [this tutorial](https://viewer.nationalmap.gov/tools/rasterconversion/Convert_IMG_to_XYZ_with_GDAL.html) from USGS.

I would love some pointers, thanks!

**Comment by stdavis** [comment]
@rkelson Do you have any suggestions for this question?

I don't know that I've ever attempted to view IMG file on my Mac. Does QGIS support them?

**Comment by rkelson** [comment]
an .img file is an Erdas Imagine file, not a disk image file, and should be
a DEM. It should be supported by QGIS

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by todrobbins** [comment]
Loaded in QGIS, thanks! Didn't realize it was that simple.
