### ISSUE TITLE
Streams files for shapefile and geodatabase are not identical.

### ISSUE THREAD

**Issue by matt439miller** [agrc/gis.utah.gov#1108]
Streams files for shapefile and geodatabase are not identical

**Comment by steveoh** [comment]
@matt439miller can you describe what you noticed not being identical? That should help @ZachBeck identify and fix the issue. Thanks for the issue!

**Comment by matt439miller** [comment]
Seems fixed now. Geodatabase I downloaded around two did not match the one
I downloaded around 5. Same geometry, very different attributes. I can
share back the geodatabase if you'd like. Pic of attribute table of the one
I downloaded follows:

[image: image.png]

Perhaps I'm the cause of the error-I did find the stream file using a
search...can't replicate it though.


Matt Miller <http://www.linkedin.com/pub/matthew-miller/4/392/583/>
PhD Student; City and Metro Planning Department, University of Utah
Graduate Research Assistant, Metropolitan Research Center
Planner, Metro Analytics
millermm@arch.utah.edu
matt439miller@gmail.com
LinkedIn <https://www.linkedin.com/in/matthew-miller-5833924/>
Google Scholar
<https://scholar.google.com/citations?user=_TFUVOwAAAAJ&hl=en>

**Comment by steveoh** [comment]
If you can send me the link to where you downloaded it from that would be helpful. I wouldn't want multiple versions of the data floating around. It wasn't on an FTP somewhere was it?

**Comment by matt439miller** [comment]
I regret I did not record the link. I don't recall it being on FTP. Let me
think... I may have pulled it off of here:
https://gis.utah.gov/data/sgid-index/, likely:
https://drive.google.com/drive/folders/0ByStJjVZ7c7mUWUzVHRteTF1YzQ. So I
may merely be conflating the NHD_streams with the other streams
dataset...that seems likely.

[image: image.png]

Perhaps both streams files ought to be on this page
<https://gis.utah.gov/data/water/lakes-rivers-dams/>, or else the non-NHD
be removed from the SGID?

Thanks for following up on this.

Matt Miller <http://www.linkedin.com/pub/matthew-miller/4/392/583/>
PhD Student; City and Metro Planning Department, University of Utah
Graduate Research Assistant, Metropolitan Research Center
Planner, Metro Analytics
millermm@arch.utah.edu
matt439miller@gmail.com
LinkedIn <https://www.linkedin.com/in/matthew-miller-5833924/>
Google Scholar
<https://scholar.google.com/citations?user=_TFUVOwAAAAJ&hl=en>

**Comment by steveoh** [comment]
I wonder if the difference is water/streams (from [sgid index](https://drive.google.com/drive/folders/0ByStJjVZ7c7mUWUzVHRteTF1YzQ)) and water/nhd streams high res from the [data page](https://gis.utah.gov/data/water/lakes-rivers-dams/#NHDStreams). I'm asking around for the difference...

**Comment by matt439miller** [comment]
Perhaps I'm confused: Is the data in the SGID intended to be distinct from
the downloadable data? Prior to the shut-down of the GIS server, and the
move to ArcGIS online, I'd always considered them identical. Although more
and more, I seem to be noticing differences in file availability. I assume
this is intentional, to save on server maintenance costs.

Is there an index anywhere of what is on the ArcGIS online vs. downloadable?

Matt Miller <http://www.linkedin.com/pub/matthew-miller/4/392/583/>
PhD Student; City and Metro Planning Department, University of Utah
Graduate Research Assistant, Metropolitan Research Center
Planner, Metro Analytics
millermm@arch.utah.edu
matt439miller@gmail.com
LinkedIn <https://www.linkedin.com/in/matthew-miller-5833924/>
Google Scholar
<https://scholar.google.com/citations?user=_TFUVOwAAAAJ&hl=en>

**Comment by steveoh** [comment]
This is a great question @matt439miller. I think @MichaelAGRC or @ZachBeck should be best able to answer that.

**Comment by MichaelAGRC** [comment]
Hey Matt.  The downloadable data should be identical to what is available in the SGID SDE instance.    There is not currently an index detailing where the data is available aside from what is on our website.  We're looking to use web hooks to update our index at gis.utah.gov for content coming from AGOL.  Have not implemented yet.

We are working on getting an SDE instance of the SGID available in the cloud for users outside the state network.  Hopefully that will alleviate some of the confusion over where data is stored and maintained.

**Comment by steveoh** [comment]
maybe a data guide wouldn't be such a bad idea for the interim. I can see it being both helpful for us to better understand our footprint and our customers.

**Comment by gregbunce** [comment]
Michael and I talked about this and determined that it will be resolved soon as part of other efforts we are working on.  aka: hang tight

**Comment by steveoh** [comment]
@gregbunce is this resolved?

**Comment by gregbunce** [comment]
i'm closing this issue as it has been resolved.  

we no longer manage downloads via our google drive (where it was possible they could get out of sync).  we now use esri's [open data hub](https://opendata.gis.utah.gov/) to manage our downloads and the data for shapefile and file geodatabase are the same (except for the occasional field name truncation in shapefiles - but this is to be expected).
