### ISSUE TITLE
Space missing in "contact section" when email and phone are provided

### ISSUE THREAD

**Issue by eneemann** [agrc/gis.utah.gov#1268]
## Issue description
At the bottom of data page descriptions, it appears that a space is consistently missing between the email address and "or", prior to listing the phone number.  It looks like this might be broad issues for all pages where both and email and phone number is presented.

#### What page is the problem visible
3 examples can be seen here:
https://gis.utah.gov/data/boundaries/zip-codes/
https://gis.utah.gov/data/boundaries/school-districts/
https://gis.utah.gov/data/transportation/roads-system/

#### Expected result
I expected:
"ENeemann@utah.gov or 385-258-4299"

#### Actual result
Instead:
"ENeemann@utah.govor 385-258-4299"

![image](https://user-images.githubusercontent.com/38330621/70158802-1820aa00-1675-11ea-8dec-b244af35fb94.png)
![image](https://user-images.githubusercontent.com/38330621/70159033-79e11400-1675-11ea-9d96-ac20ffe2cc81.png)
![image](https://user-images.githubusercontent.com/38330621/70159191-c167a000-1675-11ea-976d-19ae24029418.png)

**Comment by steveoh** [comment]
closed by a89271aea3c1356fd78c5a1cd7dd1a29df06de9a

**Comment by eneemann** [comment]
🎊
