### ISSUE TITLE
Downloads that will not be available from OpenData

### ISSUE THREAD

**Issue by rkelson** [agrc/gis.utah.gov#1297]
## Issue description

There are pages that have links to download things outside the .shp and .gdb files available from Open Data. Most of them currently reside in Drive in the _UtahSGID_Vector_ folder. A couple examples are reports, supporting documents, schemas, etc.
Not sure to what degree we should utilize the [agrc_public_share.](https://drive.google.com/open?id=0ByStJjVZ7c7mMFlBSTNXYzVnb3c)

#### What page is the problem visible

https://gis.utah.gov/data/water/flood-areas/
https://gis.utah.gov/data/geoscience/alluvial-fans/
https://gis.utah.gov/data/transportation/roads-system/

#### Expected result

Download to work with no _sharing_ issues

#### Actual result

somewhere in between where we were and where we are going

![image](https://user-images.githubusercontent.com/6200941/71419712-11f76b00-262e-11ea-8320-bbc6695e5c1d.png)

**Comment by steveoh** [comment]
I think it would be best to move everything to the agrc public drive share and we can remove the entire sgid vector folder when we are finished.

**Comment by todrobbins** [comment]
How stable are the URLs for the public drive share?

**Comment by steveoh** [comment]
Super stable. We've been using them for a few years.
