### ISSUE TITLE
Update Public Safety page download links

### ISSUE THREAD

**Issue by eneemann** [agrc/gis.utah.gov#1330]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
The download links on the Public Safety page need to be updated.  Remove the package download button and point the individual downloads to Open Data.  Datasets include:

- Correctional Facilities
- Fire Stations
- Law Enforcement
- PSAP Locations
- PSAP Boundaries
- State Agency Dispatch

#### What page is the problem visible
https://gis.utah.gov/data/society/public-safety/

#### Expected result
I expected: The download links to point to the current data in Open Data.

#### Actual result
Instead: The download links point to old data on google drive.

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
The plan is to do this with every dataset on the gis.utah.gov website. The issues we have been having with open data has slowed the progress. But, if you are ok with the issues we have been having and they will help with the data currency, we can convert these layer. It's fairly simple. I can show you the steps, or rick is familiar with the process.

**Comment by eneemann** [comment]
Yeah, I thought it might be part of blanket task.  In this case, I had a PSAP Ops Manager contact me because a layer was out-of-date.  I updated the data last week and it got pushed to Open Data, but our page link will still take you to old data on G Drive.  If you can show me the steps and the proper link format, I'll update these.

**Comment by steveoh** [comment]
Do you know the backseat driver schedule for that data? It should still be getting updated on g drive.

**Comment by eneemann** [comment]
I do not know the schedule.

**Comment by stdavis** [comment]
@eneemann Can you get me a list of the SGID layers that are associated with these downloads and I'll check the configs in backseat driver.

**Comment by eneemann** [comment]
@stdavis The SGID layers are listed below.  The only ones that I updated last week were the PSAP Boundaries and Locations.
SOCIETY.CorrectionalFacilities
SOCIETY.FireStations
SOCIETY.LawEnforcement
SOCIETY.PSAPBoundaries
SOCIETY.PSAPLocations
SOCIETY.StateAgencyDispatch

**Comment by stdavis** [comment]
These were all marked as either `demand` or `annual`. I updated them to daily and ran the script again to update them. Once we get central change detection up-and-running, I can point backseat driver at it and this problem should be solved.

Ref: https://github.com/agrc/backseat-driver/commit/337ccae3601a273d4e3bead30d13e81f253753f7

**Comment by steveoh** [comment]
@eneemann did you talk to @rkelson at all about the migration steps? If not hit me up and I can show you.

**Comment by eneemann** [comment]
@steveoh Yeah, we talked about it today, so I'll give it a shot and try to update the page tomorrow or Friday.  I'll try to document the process, too.  Give a close review to make sure I'm not screwing something up with the PR comes through.

**Comment by steveoh** [comment]
ok make a draft and start slow and I can make sure you're on the right path

**Comment by eneemann** [comment]
Meant to close this one when the pull request was merged.
