### ISSUE TITLE
problem getting lite basemap

### ISSUE THREAD

**Issue by dugorama** [agrc/gis.utah.gov#1362]
## Issue description

hey, trying to use AGRC data, but no matter how what, including signing up, your web pages just redirect me to the sign up page where I suppose you want to recollect my email address over and over.  Or not?  Amusingly, I passed by your page that claims your last system issue was in September.  

can't get past your sign up page, regardless of the fact that I have signed up.  no matter how I approach you.  I just want a lite utah basemap.  please?
doug.tharp@utah.edu
dugorama@gmail.com

#### What page is the problem visible

http://gis.utah.gov/

![image](https://user-images.githubusercontent.com/22604956/76808230-ac3df980-67ac-11ea-94dd-cc845f1b6507.png)

**Comment by steveoh** [comment]
It looks like you are signing up for our newsletter... If you want a to sign up for the discover imagery and base map service, there are google docs for that on the same page you are viewing... https://gis.utah.gov/discover/#sign-up. 

It appears that you are a student, so your professor may already have an organization account to access the service. Have you asked them?

You will also need software to connect to use the base map services. They are not downloadable from our website.

Thanks for checking our status page but this is not an issue with our system.

**Comment by dugorama** [comment]
Hey, thank you. It was not obvious to me how to sign in. So I am indeed a
Geography student. I'll find another way to a base map I suspect.

**Comment by steveoh** [comment]
No problem. There is no sign in on our website for the discover services. It seems that you are confused at how to access the services or you have some incorrect assumptions of what the services are. If you can explain what you are wanting to do, a way to base map, is very vague, we can try to help you. 

Are you expecting to use the base maps in the browser?

**Comment by dugorama** [comment]
No, I wanted to put it under a map I'm making of tree growth in parts of
Southern Utah. More soon

**Comment by steveoh** [comment]
What software are you using to make the map? Your lack of details is not helping your cause.

**Comment by steveoh** [comment]
I'm closing this because I think we did all we can for this person.
