### ISSUE TITLE
show base maps for each scale

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#1375]
Right now we show a set of the scales available from our tiled base maps. Is it complete?

I think it would be helpful to show which services use which levels on this page. 

https://github.com/agrc/gis.utah.gov/blob/master/developer/base-maps/basemap-scales/index.md

https://github.com/agrc-widgets/kitchen-sink/blob/master/packages/layer-selector/Discover.js has the scale levels per service

We can try to do this with css or fallback to an image?

**Comment by stdavis** [comment]
I think that this would still be good to look at at some point.

**Comment by steveoh** [comment]
Seems to be not worth the effort.
