### ISSUE TITLE
Hey I am having issues every month when I try to get data off the crashmapping site. Most of the time it won't load and says there are security issues. 

### ISSUE THREAD

**Issue by savk22** [agrc/gis.utah.gov#1476]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having

#### What page is the problem visible
http://gis.utah.gov/

#### Expected result
I expected:

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by nathankota** [comment]
@savk22 This issue cannot be reproduced. Data download is working normally from https://gis.utah.gov/developer/applications/vehicle-collision/
