### ISSUE TITLE
Replace drive links with open data

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#1521]
We are taking advantage of the backend provided by open data to provide current downloads in useful formats without having to manage duplicate files. Checkout the [readme](https://github.com/agrc/gis.utah.gov#hub-downloads) for the syntax of hub downloads.

## 911

- [x] [911](https://github.com/agrc/gis.utah.gov/blob/master/data/911/index.html) (not in open data, but moved download to [agrc_public_share](https://drive.google.com/drive/folders/1TVXK10eW6SmblzcUoDq5_VGg4kGDkBvV))

## address-geocoders-locators

- [x] [address-geocoders-locators](https://github.com/agrc/gis.utah.gov/blob/master/data/address-geocoders-locators/index.html) (not in open data, but moved download to [agrc_public_share](https://drive.google.com/drive/folders/1TVXK10eW6SmblzcUoDq5_VGg4kGDkBvV))

## boundaries

- [x] [citycountystate](https://github.com/agrc/gis.utah.gov/blob/master/data/boundaries/citycountystate/index.html)
- [x] [zip-codes](https://github.com/agrc/gis.utah.gov/blob/master/data/boundaries/zip-codes/index.html)
- [x] [wilderness](https://github.com/agrc/gis.utah.gov/blob/master/data/boundaries/wilderness/index.html)
- [x] [school-districts](https://github.com/agrc/gis.utah.gov/blob/master/data/boundaries/school-districts/index.html)
- [x] [conservation-districts](https://github.com/agrc/gis.utah.gov/blob/master/data/boundaries/conservation-districts/index.html)

## cadastre

- [x] [plss](https://github.com/agrc/gis.utah.gov/blob/master/data/cadastre/plss/index.html)

## demographic

- [x] [census](https://github.com/agrc/gis.utah.gov/blob/master/data/demographic/census/index.html)

## economy

- [x] [taxingareas](https://github.com/agrc/gis.utah.gov/blob/master/data/economy/taxingareas/index.html)
- [x] [enterprise-zones](https://github.com/agrc/gis.utah.gov/blob/master/data/economy/enterprise-zones/index.html)

## energy

- [x] [uranium](https://github.com/agrc/gis.utah.gov/blob/master/data/energy/uranium/index.html)
- [x] [renewable-energy](https://github.com/agrc/gis.utah.gov/blob/master/data/energy/renewable-energy/index.html)
- [x] [energy-generation](https://github.com/agrc/gis.utah.gov/blob/master/data/energy/energy-generation/index.html)
- [x] [oil-gas](https://github.com/agrc/gis.utah.gov/blob/master/data/energy/oil-gas/index.html)
- [x] [coal](https://github.com/agrc/gis.utah.gov/blob/master/data/energy/coal/index.html)

## environment

- [x] [drinking-water-systems-protection-zones](https://github.com/agrc/gis.utah.gov/blob/master/data/environment/drinking-water-systems-protection-zones/index.html)
- [x] [deq-land-related-contaminant-cleanup-sites](https://github.com/agrc/gis.utah.gov/blob/master/data/environment/deq-land-related-contaminant-cleanup-sites/index.html)
- [x] [deq-air-related-contaminant-cleanup-sites](https://github.com/agrc/gis.utah.gov/blob/master/data/environment/deq-air-related-contaminant-cleanup-sites/index.html)

## farming

- [x] [grazing-improvements](https://github.com/agrc/gis.utah.gov/blob/master/data/farming/grazing-improvements/index.html)

## geoscience

- [x] [quaternary-faults](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/quaternary-faults/index.html)
- [x] [geochronology](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/geochronology/index.html)
- [x] [soil](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/soil/index.html)
- [x] [alluvial-fans](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/alluvial-fans/index.html)
- [x] [avalanche](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/avalanche/index.html)
- [x] [landslides](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/landslides/index.html)
- [x] [earthquakes](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/earthquakes/index.html)
- [x] [aquifers](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/aquifers/index.html)

## health

- [x] [health-districts](https://github.com/agrc/gis.utah.gov/blob/master/data/health/health-districts/index.html)
- [x] [emergency-regions](https://github.com/agrc/gis.utah.gov/blob/master/data/health/emergency-regions/index.html)
- [x] [health-small-statistical-areas](https://github.com/agrc/gis.utah.gov/blob/master/data/health/health-small-statistical-areas/index.html)
- [x] [health-care-facilities](https://github.com/agrc/gis.utah.gov/blob/master/data/health/health-care-facilities/index.html)

## indices

- [x] [auto-correlated-dem-indices](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/auto-correlated-dem-indices/index.html)
- [x] [contours-indices](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/contours-indices/index.html)
- [x] [usgs-topo-indices](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/usgs-topo-indices/index.html)
- [x] [national-grid-index](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/national-grid-index/index.html)
- [x] [usgs-dem-indices](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/usgs-dem-indices/index.html)
- [x] [lidar-indices](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/lidar-indices/index.html)
- [x] [aerial-photography-indices](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/aerial-photography-indices/index.html)

_indices are hidden and not in open data. the plan is to move them to the agrc share folder_

## location

- [x] [u-s-postal-service](https://github.com/agrc/gis.utah.gov/blob/master/data/location/u-s-postal-service/index.html)
- [x] [gnis](https://github.com/agrc/gis.utah.gov/blob/master/data/location/gnis/index.html)
- [x] [building-footprint](https://github.com/agrc/gis.utah.gov/blob/master/data/location/building-footprint/index.html)
- [x] [address-data](https://github.com/agrc/gis.utah.gov/blob/master/data/location/address-data/index.html)

## planning

- [x] [water-related-land](https://github.com/agrc/gis.utah.gov/blob/master/data/planning/water-related-land/index.html)

## political

- [x] [2002-2011-house-senate-congressional-districts](https://github.com/agrc/gis.utah.gov/blob/master/data/political/2002-2011-house-senate-congressional-districts/index.html)
- [x] [2012-2021-house-senate-congressional-districts](https://github.com/agrc/gis.utah.gov/blob/master/data/political/2012-2021-house-senate-congressional-districts/index.html)
- [x] [judicial-districts](https://github.com/agrc/gis.utah.gov/blob/master/data/political/judicial-districts/index.html)
- [x] [voter-precincts](https://github.com/agrc/gis.utah.gov/blob/master/data/political/voter-precincts/index.html)

## recreation

- [x] [golf-courses](https://github.com/agrc/gis.utah.gov/blob/master/data/recreation/golf-courses/index.html)
- [x] [trails](https://github.com/agrc/gis.utah.gov/blob/master/data/recreation/trails/index.html)
- [x] [local-parks](https://github.com/agrc/gis.utah.gov/blob/master/data/recreation/local-parks/index.html)
- [x] [boat-ramps](https://github.com/agrc/gis.utah.gov/blob/master/data/recreation/boat-ramps/index.html)
- [x] [ski-areas](https://github.com/agrc/gis.utah.gov/blob/master/data/recreation/ski-areas/index.html)

## society

- [x] [state-facilities](https://github.com/agrc/gis.utah.gov/blob/master/data/society/state-facilities/index.html)
- [x] [places-of-worship](https://github.com/agrc/gis.utah.gov/blob/master/data/society/places-of-worship/index.html)
- [x] [cemeteries](https://github.com/agrc/gis.utah.gov/blob/master/data/society/cemeteries/index.html)
- [x] [blm-field-offices-forest-service-stations](https://github.com/agrc/gis.utah.gov/blob/master/data/society/blm-field-offices-forest-service-stations/index.html)
- [x] [liquor-stores](https://github.com/agrc/gis.utah.gov/blob/master/data/society/liquor-stores/index.html)
- [x] [schools-libraries](https://github.com/agrc/gis.utah.gov/blob/master/data/society/schools-libraries/index.html)
- [x] [state-fuel-sites](https://github.com/agrc/gis.utah.gov/blob/master/data/society/state-fuel-sites/index.html)

## transportation

- [x] [air](https://github.com/agrc/gis.utah.gov/blob/master/data/transportation/air/index.html)
- [x] [transit](https://github.com/agrc/gis.utah.gov/blob/master/data/transportation/transit/index.html)
- [x] [street-network-analysis](https://github.com/agrc/gis.utah.gov/blob/master/data/transportation/street-network-analysis/index.html) (not in open data, but moved download to [agrc_public_share](https://drive.google.com/drive/folders/1TVXK10eW6SmblzcUoDq5_VGg4kGDkBvV))
- [x] [roads-system](https://github.com/agrc/gis.utah.gov/blob/master/data/transportation/roads-system/index.html)
- [x] [railroads](https://github.com/agrc/gis.utah.gov/blob/master/data/transportation/railroads/index.html)

## utilities

- [x] [broadband-internet](https://github.com/agrc/gis.utah.gov/blob/master/data/utilities/broadband-internet/index.html)
- [x] [telephone-infrastructure-and-rural-telcom-boundaries](https://github.com/agrc/gis.utah.gov/blob/master/data/utilities/telephone-infrastructure-and-rural-telcom-boundaries/index.html)

## water

- [x] [flood-areas](https://github.com/agrc/gis.utah.gov/blob/master/data/water/flood-areas/index.html)
- [x] [historic-lake-bonneville](https://github.com/agrc/gis.utah.gov/blob/master/data/water/historic-lake-bonneville/index.html)
- [x] [watersheds](https://github.com/agrc/gis.utah.gov/blob/master/data/water/watersheds/index.html)
- [x] [lakes-rivers-dams](https://github.com/agrc/gis.utah.gov/blob/master/data/water/lakes-rivers-dams/index.html)
- [x] [water-rights-regions](https://github.com/agrc/gis.utah.gov/blob/master/data/water/water-rights-regions/index.html)

#### Expected result

All drive.google.com should be replaced or if not available the data should be moved to the public share re: #1297

**Comment by gregbunce** [comment]
thanks for getting this going.  i will move 911 (it's an fgdb) and the roads (shp that's too large for open data) to the public share.

also, I'll remove the remaining transportation and trails data links.

I've added it to my list of items for the next sgid road update (first week of Nov)

matt and I are meeting with esri next week to chat about interoperability etc, and I plan on bringing up the file size download limit (that's affecting the roads.shp)

**Comment by rkelson** [comment]
I plan to tackle Society next

**Comment by brigsz** [comment]
Okay, I looked things over and I see the pattern of how this is done.  I need to speak with someone to make sure I am not going to make a mess.  It seems pretty straightforward, putting in the hub: etc

**Comment by rkelson** [comment]
what is tricky is some pages can have a combination of Hub: download links and related resource that are HTML links to the open data pages and possibly agrc_public_share links for things not in Open Data.

**Comment by rkelson** [comment]
I am going to work on Boundaries next

**Comment by rkelson** [comment]
we could probably close this. Geocron is Zach's problem and fuel sites is a WIP

**Comment by steveoh** [comment]
Ok, I'd rather wait until it everything is complete to close this. I'll add the waiting tag for @ZachBeck and the state fuel site project.

**Comment by ZachBeck** [comment]
I haven't been involved with the fuel site project.

**Comment by steveoh** [comment]
> I haven't been involved with the fuel site project.

Yes I am aware. But rick called you out on geochronology which is why I mentioned you.

**Comment by ZachBeck** [comment]
I thought I did that here https://github.com/agrc/gis.utah.gov/pull/1488

**Comment by steveoh** [comment]
Ok, I think I need to be brought back to the same page. I was under the impression that Gordon was going to host all of those datasets on their arcgis online which would then make all of those urls incorrect. Do we need to have a quick chat to move forward with this?

**Comment by ZachBeck** [comment]
Shoot, you're right. We were going to start with quaternary faults but I'll have him share his geochronlogy layers with our Geoscience group and then I'll delete our geochronology from agol if his looks good. Last time I checked no one has been using our geochronology so I don't feel bad about deleting it.

**Comment by steveoh** [comment]
Yah since the web pages haven't been published and we didn't introduce the services through porter, i am also ok with that decision

**Comment by stdavis** [comment]
These links are going to have to be updated to use the agol id rather than the item title at some point. Seems like they are redirected at the moment but I'm not sure how long those will last.

Here's a search that shows them: https://github.com/agrc/gis.utah.gov/search?q=https%3A%2F%2Fopendata.gis.utah.gov%2Fdatasets%2Futah

**Comment by steveoh** [comment]
interesting choice esri. most of these can be handled by the include and front matter but these static ones will need to be done manually. Have you spoken to anyone about the redirect longevity?

**Comment by stdavis** [comment]
> Have you spoken to anyone about the redirect longevity?

No. I noticed that it was redirecting to the id-based routes today. I did notice that this one is already broken: https://opendata.gis.utah.gov/datasets/utah-oil-and-gas-well-locations/explore, although I'm not 100% sure that was the original URL. That AGOL item is a bit of a mess right now that I'm trying to get straightened out with OGM.

**Comment by steveoh** [comment]
> item id is used as a fallback in case esri can’t generate the human readable url. There are organization configurations that prevent esri from ever generating the human readable url (e.g. anonymous access is disabled for the org) and there are times when our jobs system is catching up and hasn’t generated the url yet.
>
> esri noticed many instances recently displaying ids when they were expecting human readable urls, and they eventually caught up
>
> relatedly esri is working on a couple of fixes for redirects not working as expected, particularly for the old table routes and between /about and /explore

Based on this, I think you might have been noticing slow jobs and we should be ok?

**Comment by stdavis** [comment]
@ZachBeck & @steveoh: So is Geochronology finished? Can this issue be closed?

@steveoh: What else needs to happen with the state fuel sites that you mentioned?

**Comment by ZachBeck** [comment]
Geochronology is good to go

**Comment by steveoh** [comment]
I have zero memory of state fuel sites. @rkelson whats the WIP status with that?

**Comment by rkelson** [comment]
I don't recall any WIP

Rick Kelson
Utah Geospatial Resource Center (UGRC)
*Yes we've changed our name
<https://gis.utah.gov/agrc-name-change-to-utah-geospatial-resource-center-ugrc/>*
801.433.7891
gis.utah.gov

**Comment by stdavis** [comment]
I think that this issue can be closed then. Feel free to re-open if anyone feels differently.

**Comment by steveoh** [comment]
![clap](https://media.giphy.com/media/37Ez5CZ8P0jSM/giphy.gif)
