### ISSUE TITLE
drive links in non data pages

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#1565]
# posts

- [x] [mapping-spotlight-salt-lake-city-geoportal](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2014-04-25-mapping-spotlight-salt-lake-city-geoportal.md)
- [x] [utah-acquires-high-resolution-aerial-photography-license](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2015-02-02-utah-acquires-high-resolution-aerial-photography-license.md)
- [x] [big-happenings-with-public-land-survey-system-gis](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2015-10-30-big-happenings-with-public-land-survey-system-gis.md)
- [x] [evolving-utah-sgid-web-services-a-proposal](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2015-11-27-evolving-utah-sgid-web-services-a-proposal.md)
- [x] [survey-monument-replacement-and-restoration-county-grant-program](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2016-01-27-survey-monument-replacement-and-restoration-county-grant-program.md)
- [x] [why-i-speak-at-conferences-and-you-should-to](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2016-04-01-why-i-speak-at-conferences-and-you-should-to.md)
- [x] [25th-anniversary-state-geographic-information-database](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2016-05-24-25th-anniversary-state-geographic-information-database.md)
- [x] [data-schema-released-for-expanded-gis-parcel-sharing](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2016-07-07-data-schema-released-for-expanded-gis-parcel-sharing.md)
- [x] [maps-on-the-hill-2017-contest-winners](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2017-02-23-maps-on-the-hill-2017-contest-winners.md)
- [x] [rethinking-geocoders-adding-local-vernacular-into-the-build-process](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2017-06-27-rethinking-geocoders-adding-local-vernacular-into-the-build-process.md)
- [x] [major-updates-coming-to-roads-data-model](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2017-08-15-major-updates-coming-to-roads-data-model.md)
- [x] [dumbing-down-terrain-with-contour-polygons](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2017-11-27-dumbing-down-terrain-with-contour-polygons.md)
- [x] [3-dep-lidar-proposal-2018](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2017-12-14-3-dep-lidar-proposal-2018.md)
- [x] [maps-on-the-hill-2018](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2018-02-05-maps-on-the-hill-2018.md)
- [x] [2018-utah-lidar-acquisition](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2018-05-17-2018-utah-lidar-acquisition.md)
- [x] [survey-monument-replacement-and-restoration-county-grant-program-2018-updates](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2018-09-12-survey-monument-replacement-and-restoration-county-grant-program-2018-updates.md)
- [x] [upcoming-vector-tile-base-maps](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2018-09-12-upcoming-vector-tile-base-maps.md)
- [x] [multi-modal-travel-shed-analysis-project](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2018-11-07-multi-modal-travel-shed-analysis-project.md)
- [x] [yearly-update-for-tax-entities-and-areas](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2019-02-14-yearly-update-for-tax-entities-and-areas.md)
- [x] [sgid-then-and-now](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2019-06-11-sgid-then-and-now.md)
- [x] [2019-ugic-annual-conference-recap](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2019-06-20-2019-ugic-annual-conference-recap.md)
- [x] [3-dep-lidar-proposal-2020](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2019-11-04-3-dep-lidar-proposal-2020.md)
- [x] [2020-utah-lidar-acquisition](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2020-05-13-2020-utah-lidar-acquisition.md)
- [x] [utah-sgid-statewide-roads-data-layer-updates-05202020](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2020-05-20-utah-sgid-statewide-roads-data-layer-updates-05202020.md)
- [x] [utah-sgid-statewide-roads-data-layer-updates-06242020](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2020-06-24-utah-sgid-statewide-roads-data-layer-updates-06242020.md)
- [x] [utah-sgid-statewide-roads-data-layer-updates-07282020](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2020-07-28-utah-sgid-statewide-roads-data-layer-updates-07282020.md)
- [x] [utah-sgid-statewide-roads-data-layer-updates-09042020](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2020-09-04-utah-sgid-statewide-roads-data-layer-updates-09042020.md)
- [x] [utah-sgid-statewide-roads-data-layer-updates-10092020](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2020-10-09-utah-sgid-statewide-roads-data-layer-updates-10092020.md)
- [x] [utah-sgid-statewide-roads-data-layer-updates-11062020](https://github.com/agrc/gis.utah.gov/blob/master/_posts/2020-11-06-utah-sgid-statewide-roads-data-layer-updates-11062020.md)

# data pages

- [x] [911](https://github.com/agrc/gis.utah.gov/blob/master/data/911/index.html)

## address

- [x] [locators](https://github.com/agrc/gis.utah.gov/blob/master/data/address-geocoders-locators/index.html)
- [x] [luca](https://github.com/agrc/gis.utah.gov/blob/master/data/address/census-luca-2020.md)

## bioscience

- [x] [bioscience](https://github.com/agrc/gis.utah.gov/blob/master/data/bioscience/index.html)

## boundaries

- [x] [boundaries](https://github.com/agrc/gis.utah.gov/blob/master/data/boundaries/index.html)

## cadastre

- [x] [cadastre](https://github.com/agrc/gis.utah.gov/blob/master/data/cadastre/plss/index.html)
- [x] [parcels](https://github.com/agrc/gis.utah.gov/blob/master/data/cadastre/parcels/index.html)

## demographic

- [x] [demographic](https://github.com/agrc/gis.utah.gov/blob/master/data/demographic/census/index.html)

## elevation

- [x] [elevation](https://github.com/agrc/gis.utah.gov/blob/master/data/elevation-and-terrain/index.html)

## geoscience

- [x] [geoscience](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/index.html)
- [x] [alluvial fans](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/alluvial-fans/index.html)
- [x] [geochronology](https://github.com/agrc/gis.utah.gov/blob/master/data/geoscience/geochronology/index.html)

## health

- [x] [emergency regions](https://github.com/agrc/gis.utah.gov/blob/master/data/health/emergency-regions/index.html)

## indicies

- [ ] [indices](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/index.html)
- [ ] [aerial](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/aerial-photography-indices/index.html)
- [ ] [dem](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/auto-correlated-dem-indices/index.html)
- [ ] [contours](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/contours-indices/index.html)
- [ ] [lidar](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/lidar-indices/index.html)
- [ ] [national grid](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/national-grid-index/index.html)
- [ ] [usgs dem](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/usgs-dem-indices/index.html)
- [ ] [usgs topo](https://github.com/agrc/gis.utah.gov/blob/master/data/indices/usgs-topo-indices/index.html)

## political

- [x] [voter precincts](https://github.com/agrc/gis.utah.gov/blob/master/data/political/voter-precincts/index.html)

## recreation

- [x] [trails](https://github.com/agrc/gis.utah.gov/blob/master/data/recreation/trails/index.html)

## transportation

- [x] [roads](https://github.com/agrc/gis.utah.gov/blob/master/data/transportation/roads-system/index.html)
- [x] [street network](https://github.com/agrc/gis.utah.gov/blob/master/data/transportation/street-network-analysis/index.html)

## utilities

- [x] [broadband](https://github.com/agrc/gis.utah.gov/blob/master/data/utilities/broadband-internet/index.html)

## water

- [x] [flood](https://github.com/agrc/gis.utah.gov/blob/master/data/water/flood-areas/index.html)

# Pages

- [x] [about 911](https://github.com/agrc/gis.utah.gov/blob/master/about/gis-for-911/index.html)
- [x] [about moth](https://github.com/agrc/gis.utah.gov/blob/master/about/maps-on-the-hill/index.md)
- [x] [about strategic plan](https://github.com/agrc/gis.utah.gov/blob/master/about/strategic-and-business-plans/index.html)
- [x] [developer vehicle collisions](https://github.com/agrc/gis.utah.gov/blob/master/developer/applications/vehicle-collision/index.html)
- [x] [gis data sharing](https://github.com/agrc/gis.utah.gov/blob/master/gis-data-sharing/index.md)

refs #1521

**Comment by rkelson** [comment]
does this list only include drive links or are docs.google.com links also part of the list?

**Comment by steveoh** [comment]
> does this list only include drive links or are docs.google.com links also part of the list?

this is only drive links.

**Comment by rkelson** [comment]
**Bioscience** - Waiting for DNR to host the WRI data and then share it with our open data

**Comment by rkelson** [comment]
**Trails** - Needs the data model links possibly moved to public share by the data steward

**Comment by rkelson** [comment]
**Health** - _Emergency Regions_ has been Removed
https://github.com/agrc/porter/issues/77

**Comment by steveoh** [comment]
lets ignore indices and close this.
