### ISSUE TITLE
Census Shapefiles are returning a 404 error

### ISSUE THREAD

**Issue by danames** [agrc/gis.utah.gov#1572]
## Issue description
Go to https://gis.utah.gov/data/demographic/census/ and scroll down to the 2010 Census data. Try to download the census blocks shapefiles and the other shapefiles in that block. They return a 404 error. The geodatabases seem to work though. But the shapefiles are what I was going for and sadly they seem broken. 
![image](https://user-images.githubusercontent.com/3472628/99453678-89875600-28e2-11eb-975e-b529375daff1.png)

#### What page is the problem visible
https://gis.utah.gov/data/demographic/census/

#### Expected result
I expected: shapefile downloads

#### Actual result
Instead: 404 error.

**Comment by danames** [comment]
![image](https://user-images.githubusercontent.com/3472628/99453721-9c018f80-28e2-11eb-9be2-b2e6cd75936f.png)


Here is the error for this particular shapefile:

https://opendata.arcgis.com/datasets/8fa5d65451694f64b05f17d9e5f9d67e_0.shp

**Comment by steveoh** [comment]
Thank you for reporting this. I have pushed the fix for this. The site is rebuilding now and will deploy shortly.

**Comment by MichaelAGRC** [comment]
Hi Dan,

We'll have to take a look at those links, but if you need the data in shapefile format you can download it from our opendata site:
https://opendata.gis.utah.gov/search?groupIds=425d4c68c6064245a6efdc31333af1ef

**Comment by steveoh** [comment]
@rkelson did you add any other `.shp` file extensions that should be `.zip` when working on #1521

**Comment by danames** [comment]
I can confirm that the links to the Census Blocks shapefile zip file works
now.
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
https://ceen.byu.edu/directory/dan-p-ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************
