### ISSUE TITLE
geojson api no longer available?

### ISSUE THREAD

**Issue by cmichaud92** [agrc/gis.utah.gov#1579]
I'm pretty new to AGRC data services, however, I was working on a project several months ago and fetched data via the AGRC geojson API.  I have returned to the project and now I cant find the geojson API, the GeoService API is available, however, cannot use it (I am using R and `sf::st_read()`). I have somewhat resolved the issue by accessing data via the ArcGIS Hub, however, I like the layout of AGRC and prefer to use this source. Please let me know if I am missing something!
Thanks

**Comment by steveoh** [comment]
What is the geojson resource url that is no longer available that you had in your code?

**Comment by cmichaud92** [comment]
@steveoh , Thanks for the quick response, Again, I am new to AGRC and remote access to spatial data, and this may be a non issue... 

The geojson resource url is still available
```
# `read_sf()` will handle "GeoJSON" APIs
cnty_sf <- read_sf(dsn = "https://opendata.arcgis.com/datasets/90431cac2f9f49f4bcf1505419583753_0.geojson")

mapview(cnty_sf2)

plants <- read_sf(dsn = "https://opendata.arcgis.com/datasets/0fd6aa168ea2463c8adce143a06812ce_0.geojson")
``` 
Both of these url's still function properly, I am able to access the data.  My trouble comes from locating the geojson url on AGRC to access new data.  Currently I search the AGRC site for useful data and when I find it I copy the json url and paste into my code.

Utah airports for example... I select `Utah Airport Locations: SGID Open Data Downloads and APIs` and then click on `APIs` dropdown.  All that is available is the geoservice url.  I'm sure there used to be a geojson url option available from this dropdown also.  Now I need to search ArcGIS hub for the data of interest and when I click on the `APIs` tab here I have both geoservice and geojson available.  I'd like to restrict my manual searching to one website if possible.  I'm also open to alternative workflows, however, at this point I'm already in the weeds. Anyway, I hope this makes sense and thank you for your time.

**Comment by steveoh** [comment]
I appreciate that you like the layout of the AGRC website! 

We have historically hosted shapefile and file geodatabases from the AGRC website. GeoJSON has been served from our open data (hub) website. The hub download api has updated and the resource you are requesting changed slightly. 

You used to be able to click `APIs` and get a GeoJSON link from the v2 download api:

`https://opendata.arcgis.com/datasets/90431cac2f9f49f4bcf1505419583753_0.geojson`

![image](https://user-images.githubusercontent.com/325813/99988071-722aeb80-2d6e-11eb-819c-4da7b691f385.png)

Now you must click `Download Options` and then scroll to `GeoJSON` where you'll get a v3 download link: 

`http://opendata.arcgis.com/api/v3/datasets/90431cac2f9f49f4bcf1505419583753_0/downloads/data?format=geojson&spatialRefId=3857`

We link to open data service from every available data package on the AGRC website so you shouldn't have to double search. 

![image](https://user-images.githubusercontent.com/325813/99989140-83c0c300-2d6f-11eb-83f0-23a0bf97468b.png)

You should also be able to use the GeoService api. Adding a where clause of `1=1` will give you every row of the data and setting the format to `geojson` will give you the format your code is requesting.

`https://services1.arcgis.com/99lidPhWCzftIe9K/arcgis/rest/services/UtahCountyBoundaries/FeatureServer/0/query?where=1%3D1&f=geojson`

With that I will close this issue. Please continue to comment if you want to further discuss this.
