### ISSUE TITLE
Add AGRC storymap to website

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#1589]
https://storymaps.arcgis.com/stories/8be2e6de2abf442eb72f5faa8a32dd2b should be in our website somewhere as requested by @brigsz. 

@brigsz do you have anywhere in mind that you would like this? I believe a link should take off from https://gis.utah.gov/about/ under the heading Our Background.  I will look at where in the text it may fit best.

**Comment by stdavis** [comment]
paging @brigsz ...

**Comment by brigsz** [comment]
okay, I seemed to be having difficulty yesterday.  I believe a link should take off from https://gis.utah.gov/about/ under the heading Our Background. I will look at where in the text it may fit best.  I will try to find a spot in that text

**Comment by brigsz** [comment]
I think at the end of the fourth paragraph is a great place for the link to the story map.  What is the best way to communicate that?  Close this issue and open a PR with the link inserted at the end of paragraph 4?

**Comment by stdavis** [comment]
Actually, on closer inspection, the storymap is already [linked to from that page](https://github.com/agrc/gis.utah.gov/blob/c1afa06c6321e21203cdd224b881a4ff7c016457/about/index.md#L28). See the "encouraging and facilitating" text in the first paragraph. So I believe that this issue can be closed. Although, I did notice that that story map has a lot of outdated information that needs to be changed (AGRC->UGRC, office location, etc).
