### ISSUE TITLE
ArcGISPro Connect to the Open SGID instructions incorrect

### ISSUE THREAD

**Issue by rsaathoff** [agrc/gis.utah.gov#1595]
https://gis.utah.gov/sgid/open-sgid/#arcgis-pro

The instructions say to "Add Database", it should say "New Database Connection".  Also, it doesn't tell you what the password is.

![image](https://user-images.githubusercontent.com/76059382/102239070-b31ca880-3eb3-11eb-9ce3-c6787d1e71e2.png)

**Comment by steveoh** [comment]
Thanks we'll get that corrected right away.

**Comment by jacobdadams** [comment]
Thanks for reporting this. The latest commit should correct the instructions and make it more clear where to find the latest connection information.

**Comment by stdavis** [comment]
@rsaathoff We just pushed a build that addresses your valuable feedback. It should be live now. Please take a look and us know what you think.

Thanks for the issue!
