### ISSUE TITLE
geocode table

### ISSUE THREAD

**Issue by wilsonlexie** [agrc/gis.utah.gov#1699]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having
The Geocode Table tool from AGRC is linked to an outdated version of the software (I think?)

#### What page is the problem visible
http://gis.utah.gov/
This is the warning message I get after running the tool:
![image](https://user-images.githubusercontent.com/34170906/114192352-9d236f80-990a-11eb-86db-155825459f29.png)

#### Expected result
I expected:
.

#### Actual result
Instead:

.
_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by stdavis** [comment]
Hey Lexie. Thanks for submitting an issue! 

What page are you looking at? I checked the download link ("ArcGIS Pro Toolbox (starting at Pro 1.3)") on this page: https://gis.utah.gov/data/address-geocoders-locators/?GeocodingToolbox#GeocodingToolbox and it appears to download the correct version. I'm wondering if you're looking at a different page.

**Comment by wilsonlexie** [comment]
yes i downloaded from that page!

[image: Division Name] <https://airquality.utah.gov/>
*Lexie Wilson*

Air Quality Researcher, Modeler & Lead GIS Analyst
Environmental Scientist  |  Technical Analysis Section
P: (385) 306 - 6522
airquality.utah.gov
Emails to and from this email address may be considered public records and
thus subject to Utah GRAMA requirements.

**Comment by stdavis** [comment]
Can you tell me what the contents of your `tool-version.json` file are?
![image](https://user-images.githubusercontent.com/1326248/114207696-e333ff80-9919-11eb-89f8-443648521436.png)

**Comment by stdavis** [comment]
@wilsonlexie Did you ever get this figured out? If not, I'd be happy to help. I think that the next step was to see what the contents of `tool-version.json` is on your machine.

**Comment by stdavis** [comment]
Sent Lexie a message via chat today.

**Comment by stdavis** [comment]
/remind me to check on this issue in a week

**Comment by stdavis** [comment]
All is well with Lexie.

**Comment by steveoh** [comment]
Did you find out what was up with the version.json and all of that?

**Comment by stdavis** [comment]
No
