### ISSUE TITLE
Broken link to Retail Culinary Water Suppliers Dataset

### ISSUE THREAD

**Issue by sjwoodruff** [agrc/gis.utah.gov#1724]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
None of the retail culinary water suppliers data links are currently working.

#### What page is the problem visible
http://gis.utah.gov/

#### Expected result
I expected: A download of the retail culinary providers boundaries in any GIS format.

#### Actual result
Instead: Broken Links

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_
![image](https://user-images.githubusercontent.com/25542543/117889739-485c7700-b271-11eb-9901-9b88838064bb.png)
![image](https://user-images.githubusercontent.com/25542543/117889772-51e5df00-b271-11eb-987e-f52137ef7dbe.png)

**Comment by steveoh** [comment]
Thanks for reporting this. We just swapped this out via https://github.com/agrc/porter/issues/130. It looks like we struck out updating the website when it actually needed some action. I'll get that taken care of now.

**Comment by sjwoodruff** [comment]
Thanks Steve. Been years since I've logged into my Github. Thanks for the quick response!

**Comment by steveoh** [comment]
The data links are working now @sjwoodruff except for the export file geodatabase since dnr has not enabled that. We will reach out to them to get that turned on and if they choose not to we will hide the link. Again thanks for the heads up!
