### ISSUE TITLE
Survey Monument Replacement and Restoration Link is broken

### ISSUE THREAD

**Issue by stdavis** [agrc/gis.utah.gov#1771]
https://github.com/agrc/gis.utah.gov/blob/f1e65a138941898dc4706dd59bec9ef54fed795f/about/code/index.html#L33

This link 404s. @mheagin or @seanfernandez Do you have the appropriate link?

**Comment by seanfernandez** [comment]
Did you get the correct link?

**Comment by stdavis** [comment]
No, I do not have the correct link.
