### ISSUE TITLE
Outdated and unlinked network dataset creation page?

### ISSUE THREAD

**Issue by jacobdadams** [agrc/gis.utah.gov#1774]
## Issue description
This page seems two SGID versions out of date, and I can't find a link to it from the roads data page. Time to put it to pasture?

#### What page is the problem visible
http://gis.utah.gov/data/transportation/roads-system/create-network-analysis-dataset-instructions/

**Comment by steveoh** [comment]
it looks like bert created this 10 years ago and it's referenced in https://gis.utah.gov/school-bus-routing-based-on-sgid-roads/. I am all for removing it.

**Comment by jacobdadams** [comment]
Closed with #1781
