### ISSUE TITLE
look at some logos

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#1793]
- [logo 1](https://deploy-preview-1789--gis-utah-gov.netlify.app/)
- [logo 2](https://deploy-preview-1788--gis-utah-gov.netlify.app/)
- [logo 2b](https://deploy-preview-1790--gis-utah-gov.netlify.app/)
- [logo 3](https://deploy-preview-1791--gis-utah-gov.netlify.app/)
- [logo 3b](https://deploy-preview-1792--gis-utah-gov.netlify.app)

**Comment by brigsz** [comment]
Logo 3 is possible, Logo 2 is possible, the rest, not so much

**Comment by jacobdadams** [comment]
I think logo 1 might work with a redesigned header, it definitely doesn't work as a straight-up drop-in replacement. 

That being said, I think I like 3 the best.

**Comment by steveoh** [comment]
2b or 3 for me.
