### ISSUE TITLE
Newsletter Sign up

### ISSUE THREAD

**Issue by brigsz** [agrc/gis.utah.gov#1849]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having

There is a link on this page for signing up for the newsletter.  When I hit the link it takes me to about:blank#blocked

#### What page is the problem visible
http://gis.utah.gov/  It is under News Events and Coordination there is a signup link

#### Expected result
I expected:

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
Ok, yes, if you use the link in the footer it works. I'll update that other link as well. Good catch!
