### ISSUE TITLE
Change to UGRC logos on media page

### ISSUE THREAD

**Issue by nathankota** [agrc/gis.utah.gov#1896]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
We renamed out agency and have new logos and need to replace our old logos on the media page.

#### What page is the problem visible
https://gis.utah.gov/about/media/

#### Expected result
I expected: 
To have downloadable UGRC "wavy gravy" logos

#### Actual result
Instead:
We are providing downloadable "tiara" AGRC logos

**Question:** which logos would we like to make available from 
https://drive.google.com/drive/folders/1JfTXMAsmH8vPaKUhtqBtT9MQPoufKVns 
and/or
https://drive.google.com/drive/folders/1bX0CR11C5ckH1AhePynHPZxhyvNInZZc

**Comment by steveoh** [comment]
None of the logos from the `Annas Folder` are good enough quality to share for download. We will have to recreate any of the styles if we want to provide them for download. 

My suggestion would be to have every logo for all our products available on this page.

## URGC Agency

 1. horizontal dark
 2. horizontal light
 3. vertical dark - *this design needs to be chosen and or designed*
 4. vertical light - *this design needs to be chosen and or designed*

## SGID

1. wavy
2. dark
3. light

_These are all horizontal. Do we need a vertical style?

## TURN

1. wavy
2. dark 
3. light

## Discover

1. wavy
2. dark 
3. light

## API

1. wavy
2. dark 
3. light

**Comment by steveoh** [comment]
This still need to happen.
