### ISSUE TITLE
WRLU page

### ISSUE THREAD

**Issue by TMoore24** [agrc/gis.utah.gov#1907]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
1) The primary  contact should  be changed to tmoore@utah.gov from AaronAustin@utah.gov. Feel free to confirm with Aaron.
2) Can we include a link to https://dwre-utahdnr.opendata.arcgis.com/pages/wrlu on this page. This page includes a report that is important to for understanding this dataset, it also provides all of the years this data exists which is a common request we get from people finding our data on your website. 

Thank you,
          Tom Moore

#### What page is the problem visible
https://gis.utah.gov/data/planning/water-related-land/

#### Expected result
I expected:

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by nathankota** [comment]
UGRC change log/stewardship sheet also updated.

**Comment by steveoh** [comment]
I believe all relevant pull requests for this request have been merged. Closing as completed. Thank you for the update @TMoore24 and completing these tasks @nathankota! 🚀
