### ISSUE TITLE
Add the Indices category back to the Data Categories icons

### ISSUE THREAD

**Issue by rkelson** [agrc/gis.utah.gov#1917]
We removed the Indices category from the Data Categories icons. It needs to be added back now that the webpage has been revised to remove links and references to the 10's of index layers we no longer distribute. I would add it back in but I am not sure how.

#### What page is the problem visible

- https://gis.utah.gov/
- https://gis.utah.gov/data/

#### Expected result

I expected to see the data category icon that links to the new page https://gis.utah.gov/data/indices/
And somehow get it added to Open Data although that is not a website issues.

**Comment by steveoh** [comment]
this looks complete
