### ISSUE TITLE
Where is December 2022 newsletter

### ISSUE THREAD

**Issue by brigsz** [agrc/gis.utah.gov#1988]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Missing a link to the last newsletter on gis.utah.gov

#### What page is the problem visible
https://gis.utah.gov/agrc-newsletter/

#### Expected result
I expected: The latest newsletter from December of 2022

https://mailchi.mp/9b0072ee2363/latest-updates-from-the-ugrc

#### Actual result
Instead: nothing

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
assuming you meant 2021, the link is in there.
