### ISSUE TITLE
Insecure API requests; severe vulnerability

### ISSUE THREAD

**Issue by skouzini** [agrc/gis.utah.gov#2060]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
I have a database of addresses that I want converted to Lat/Long but I realized that each request would be sent through the url, as opposed to the request body. This seems like a serious vulnerability for anyone using the API for any purpose other than casual/private. 

#### What page is the problem visible
https://api.mapserv.utah.gov/

#### Expected result
I expected:
API requests to be sent through the request body, safe from the prying eyes of anyone scraping web traffic.

#### Actual result
Instead:
Data passed through API can be easily picked up by anyone who wants to, exposing personal information.

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
HTTPS protects the whole HTTP request besides the host. The path, the parameters, cookies, http headers, and the body are all encrypted with HTTPS. An address is only an address with no PII being exposed.
