### ISSUE TITLE
denote shelved layers as such on associated web pages

### ISSUE THREAD

**Issue by rkelson** [agrc/gis.utah.gov#2080]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Not knowing what layers are _shelved_ from a layer's webpage, category overview page description, or _Related Data_ link

#### What page is the problem visible
One example is https://gis.utah.gov/data/society/places-of-worship/

#### Expected result
See somewhere on the webpage or description on a category overview page that the layer is shelved. The _shelved_ text could also link to the explanation for shelved
https://gis.utah.gov/about/policy/sgid/#shelved-datasets

#### Actual result
Going to the download link that takes you to the agol page to find the NOTE: that it is shelved
_NOTE: This dataset is an older dataset that we have removed from the SGID and 'shelved' in ArcGIS Online. There may (or may not) be a newer vintage of this dataset in the SGID._

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
I like this idea.

Do you think this shelved setting should play into the confidence scoring we are working on? Or at least compliment it somehow?

@gregbunce @jacobdadams @eneemann @nathankota

**Comment by steveoh** [comment]
@rkelson do you want to help compile a list of shelved datasets? I think it could be a fun coding exercise to get most of the way there?

**Comment by nathankota** [comment]
I like it too. It would be helpful to see a 'shelved' indicator on the data page.
> 
> Do you think this shelved setting should play into the confidence scoring we are working on? Or at least compliment it somehow?
> 
Good questions here. At one time most (all?) of the shelved items were the legitimate, trusted, high-confidence records (e.g. tax areas and entities), but not sure how that plays into a current confidence score - like if shelved items get their own scores (something simple like thumbs up or down); if they get the full gold, silver, bronze treatment; or if they all just go into the same bucket/designation within the scoring scheme.

**Comment by eneemann** [comment]
I guess 'shelved' might be pseudo-baked into the score based on the 'update schedule/currency'? Maybe depends on how we interpret that. Could we scan the AGOL items that are tagged as 'shelved' and use that to populate an icon or text box somewhere on the data pages?

Last thing...it looks like [places of worship](https://opendata.gis.utah.gov/datasets/utah-places-of-worship/) is still in OpenData.  I can't remember what prevents these layers from getting to OpenData (the 'shelved' tag?), but we may need to revisit it.

**Comment by jacobdadams** [comment]
OpenData sharing is dependent upon what groups an item is shared with. The `UGRC Shelf` group is NOT shared with Open Data. That dataset is in the `AGOLItems_shelved` table but auditor doesn't seem to be wanting to move it to the shelf group. Let me try some things.

**Comment by jacobdadams** [comment]
Ok, that was janky. AGOL showed that it wasn't shared to the group, but all the ArcGIS API for Python calls said it was (hence auditor didn't try to share it again- it thought it was already). When I went to share it manually, it said it was shared. I unshared, then reshared with `UGRC Shelf` and that seems to have kicked it loose. I'm not seeing it if I search Open Data anymore.

**Comment by steveoh** [comment]
good point @eneemann that seems good enough for me.

**Comment by steveoh** [comment]
@rkelson understanding the shelving process isn't as important as identifying the data pages on our website for shelved data

**Comment by rkelson** [comment]
@steveoh true however all I know is some folks came up with a list, did something that triggered something else to do some things. And then there is some Nightstalker piece but I figured he went to prison back in the 80's. You can search the stewardship sheet for _shelved_ but someone closer to the process might be better to provide a 'list'

**Comment by steveoh** [comment]
So you're sure you don't want to help out then?

**Comment by rkelson** [comment]
As loaded as I know that question and your intent is, sure I can help possibly after 7/11/22. Sounds like all the shelved and deprecated layers are in the UGRC_Shelved folder of our portal.
https://www.arcgis.com/sharing/rest/content/items/8e96e08c50084d2d917e0b42dfaf433e

**Comment by steveoh** [comment]
i believe this was addressed with the website rebuild
