### ISSUE TITLE
add endpoints to water pages

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#2259]
let's get this merged and when I have the time I will add endpoints: to this page and fix the Floodplains page https://gis.utah.gov/data/water/flood-areas/

_Originally posted by @rkelson in https://github.com/agrc/gis.utah.gov/issues/2258#issuecomment-1487307821_

**Comment by steveoh** [comment]
let's not let this slip through the crack @rkelson

**Comment by rkelson** [comment]
I don't recall what was needed but I think this was resolved in https://github.com/agrc/gis.utah.gov/pull/2258

**Comment by steveoh** [comment]
great!
