### ISSUE TITLE
Update Terrain thumbnail on data/base-map-and-imagery

### ISSUE THREAD

**Issue by jacobdadams** [agrc/gis.utah.gov#2428]
## Issue description
The `data/base-map-and-imagery` landing page has a Terrain thumbnail from the old basemap. I can update it with a clip from the new  basemap, but I wasn't sure if @ZachBeck can create a better one straight from the Pro project?

Or maybe this is moot while we figure out what the new website will be?

#### What page is the problem visible
http://gis.utah.gov/data/base-map-and-imagery

**Comment by ZachBeck** [comment]
I put some options in G:\Shared drives\AGRC Team\Staff\zbeck\basemap_icons 
Let me know if you have something else in mind. I guess we should change the Terrain AGOL thumbnail while we're at it.

**Comment by steveoh** [comment]
you may still want to do this but closing as this is an old page and issue
