### ISSUE TITLE
School District Boundary Alignment

### ISSUE THREAD

**Issue by d-how** [agrc/gis.utah.gov#248]
We (the Utah State Board of Education) are attempting to use the school district API to verify the district of residence for Utah students. The service functions great but the school district boundaries seem to be off in some cases. For example, Ogden City School District boundary should follow Harrisville Road and 1200 West. The boundaries seem to be shifted down and to the right when we bring your shapefile into Google Earth. See attached.

![image](https://cloud.githubusercontent.com/assets/22625888/19093299/cb50a868-8a47-11e6-85e3-d41bdeb5e97e.png)

There is a similar issue with Salt Lake and Granite.

![image](https://cloud.githubusercontent.com/assets/22625888/19093448/803dbe3c-8a48-11e6-861d-b560186b4779.png)

We've noticed the school district boundaries haven't been updated since 2015. How can we get these and other issues updated in the AGRC so it returns the correct school district?

Thank you very much for providing this service.

**Comment by steveoh** [comment]
paging @ZachBeck and @mheagin

**Comment by brigsz** [comment]
@d-how Could you call me at 801-538-3168 and we can get a plan together.  Thanks

**Comment by brigsz** [comment]
@mheagin Mike Heagin will be updating the issues outlined above.  When he completes this we will close this issue

**Comment by mheagin** [comment]
We have a mixed bag here, there are some areas that look off or shifted and can be adjusted. 
Then we have large areas where the school district would have to file a annexation to amend their boundary to go along with annexations done by cities or counties.
I have done the adjustment to the areas I felt I could, those are in the SDE data. And soon will be updated to the ArcOnline feature layer and map.
Then I created maps showing the areas that looked like they need to have an annexation, and sent those to Tax. They should review them and find out: 1. if an annexation was sent and missed by tax, 2. no annexation was submitted and would needs to be. Then make the changes and notify us about the changes. Until then there is not much more we can do.
Salt Lake County has contacted us and said the situation may be causing issues with ballots not being distributed correctly. The are looking into this for their county and will let us know any developments.
As soon as we have more information or new data I will let you know.   Mike

**Comment by d-how** [comment]
Oh great. This will certainly help. Yes, please keep me updated. Thank you
very much!

**Comment by mheagin** [comment]
At this point any more adjustments will have to be from annexations. The School Districts, and County will have to provide the documentation for this. Some of this will require a little work on their part. 
I don't expect updates to be coming in too fast now, especially since the election is over. We'll keep reminding them every couple of months but until it becomes an issue somewhere, the data is at it best that it can be.

**Comment by d-how** [comment]
Hey Mike

Thank you for your help with this. We really appreciate it. Is the updated
dataset available for download? I'd like to take a look just to see where
we're at.

Thanks again.
Derek

**Comment by mheagin** [comment]
The data is on our web site:
https://gis.utah.gov/data/boundaries/school-districts/
And the online map has been updated:
http://www.arcgis.com/home/item.html?id=f776908620be4604bfa5f96f5df5ebcb
We still have 10 areas that I need to have an annexation to before I can adjust, this includes the area with the Northwest Middle School. Tax is looking into it, if you want copies of the maps to send to the districts and see if they have a record of the annexations let me know and I can email them to you.

**Comment by d-how** [comment]
Yes, please send me the maps in question and can pass them on to my
contacts at the districts and see if we can find anything. Thank you!

**Comment by mheagin** [comment]
Maps are on there way.
![canyons_granite](https://cloud.githubusercontent.com/assets/10677659/20287326/130af5d0-aa89-11e6-8c42-62b07e499f2a.jpg)
![granite_saltlake](https://cloud.githubusercontent.com/assets/10677659/20287324/13097002-aa89-11e6-8260-682428233375.jpg)
![granite_slcity_sd](https://cloud.githubusercontent.com/assets/10677659/20287323/130965a8-aa89-11e6-9cae-992b4d8d63c0.jpg)
![murraycity_granite](https://cloud.githubusercontent.com/assets/10677659/20287322/130941f4-aa89-11e6-99dd-27d389633d77.jpg)
![ogden_weber](https://cloud.githubusercontent.com/assets/10677659/20287325/13098862-aa89-11e6-94f8-f861f92d9287.jpg)
![ogdencity_schooldist](https://cloud.githubusercontent.com/assets/10677659/20287327/130f662e-aa89-11e6-8817-cb6e59676afc.jpg)
![ogdenschooldist2](https://cloud.githubusercontent.com/assets/10677659/20287329/13186382-aa89-11e6-91bd-f4a6e7581e2a.jpg)
![provocity_schooldist](https://cloud.githubusercontent.com/assets/10677659/20287330/1319448c-aa89-11e6-992d-0143a751d693.jpg)
![saltlakecity_granite](https://cloud.githubusercontent.com/assets/10677659/20287331/131aac32-aa89-11e6-9e9d-e43f0427a469.jpg)
![saltlakecounty](https://cloud.githubusercontent.com/assets/10677659/20287328/13162d9c-aa89-11e6-96f1-26f344006412.jpg)
