### ISSUE TITLE
Review website for out of date pages

### ISSUE THREAD

**Issue by jpechmann** [agrc/gis.utah.gov#250]
Make a list of pages that are out of date, not complete, need to be edited, etc. 

Running list (please edit and add):

1. **GAP Landcover**: https://github.com/agrc/agrc.github.io/blob/master/data/bioscience-overview/gap-landcover-classification-raster/index.html 
1. https://github.com/agrc/agrc.github.io/blob/master/data/gap-landcover-classification-vector/index.html

**Comment by steveoh** [comment]
How is the list coming?

**Comment by steveoh** [comment]
closing in favor of #515
