### ISSUE TITLE
HTML in markdown issues

### ISSUE THREAD

**Issue by stdavis** [agrc/gis.utah.gov#2501]
![Image](https://github.com/agrc/gis.utah.gov/assets/1326248/1147c2d7-58c2-4d54-8932-585e1aaf2602)

Maybe it's because of the `,` in the title? 
https://github.com/agrc/gis.utah.gov/blob/d56b856db1f9b345f3e5ae43291c62dd92e7b3b9/src/content/blog/2018-01-09-transitioning-to-a-new-world-arc-pro.md#L2

**Comment by steveoh** [comment]
Try quoting it? Or it's probably from the liquid syntax on the images and links.

**Comment by steveoh** [comment]
The comma doesn't have anything to do with the malformed url. It's file based routing so it uses the file name. The issues is the html images with the liquid syntax.
