### ISSUE TITLE
Clean Up Blog Categories

### ISSUE THREAD

**Issue by stdavis** [agrc/gis.utah.gov#2503]
- [x] Come up with new list of categories
- [x] Manually categorize all posts marked as "Uncategorized"

**Comment by steveoh** [comment]
from slack...

API -> everything API related
SGID -> everything data related
SGID data updates -> roads muni updates
TURN -> everything network GPS related
Discover -> everything related to base maps and services? (there’s some overlap with SGID here)
Collaboration -> project updates through collaboration, events
Survey -> survey related things not GPS network related
Developer -> anything not related to the API
Guestblog -> for others
UGRC -> a place for UGRC to be UGRC e.g. greg’s western grid, hippocampus

**Comment by steveoh** [comment]
and done.
