### ISSUE TITLE
New blog post slash command

### ISSUE THREAD

**Issue by stdavis** [agrc/gis.utah.gov#2531]
https://github.com/agrc/templater should be migrated to match the new architecture. 

It should also just become a page within the website rather than a separate project.

- [ ] Create porter issue for deprecating the old app

**Comment by steveoh** [comment]
It could fit nicely in the collaboration pillar?

**Comment by steveoh** [comment]
we could use GitHub actions and issue comments to replace some of the templating features. Like slash commands to create a new blog post with some parameters, and it can create the file with the name, and the date in the right place, with some placeholder content to fill out in a new branch and draft pull request.

We just need to think about how non-UGRC people could do this or if they could do this. No Portor issues don’t need blog posts they need sgid index entries.

**Comment by stdavis** [comment]
I like the idea of issue templates + github actions that respond to slash commands in comments. The only bummer would be that as a user, I could create the issue but then I would have to wait for one of us to approve it before I can start working on the content. Why not just create the branch and draft PR when the issue is created? That seems like a relatively cheap operation. If it starts to become abused then we could work in checks like validating that the user who opened the issue is part of a specific team.

**Comment by steveoh** [comment]
Works for me! We need an external user story but that can come later

**Comment by steveoh** [comment]
internal story is complete.
