### ISSUE TITLE
BLM CadNSDI GIS Version 2.3 Link Broken - giving a 403 error

### ISSUE THREAD

**Issue by seanfernandez** [agrc/gis.utah.gov#2538]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having

On this page https://gis.utah.gov/data/cadastre/plss/   Under Downloads and Web Services the BLM CadNSDI GIS Version 2.3 gets a 403 error

#### What page is the problem visible
http://gis.utah.gov/

https://gis.utah.gov/data/cadastre/plss/ 

#### Expected result
I expected:

To be able to download a zip file, or be connected to a web service

#### Actual result
Instead:
403 error 

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_
![image](https://github.com/agrc/gis.utah.gov/assets/9937422/9784dfde-aa1d-4abf-aa9d-f136a4609481)

**Comment by steveoh** [comment]
I'm assuming that maybe this link was destroyed when mike retired. Do you possibly have a copy that you can give @gregbunce to put the in long term google drive share?

**Comment by steveoh** [comment]
@gregbunce @DenisePeterson @seanfernandez 🔔

**Comment by steveoh** [comment]
Is this still an issue? @seanfernandez please close this if the works been completed.

**Comment by DenisePeterson** [comment]
In August 2024, I uploaded the new CadNSDI data from BLM to our Google Drive and updated the link so the new data could be downloaded.
