### ISSUE TITLE
Migrate .doc's to google docs

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#2569]
we are serving .doc files for auto-correlated dems and other projects. There isn't really a reason to distribute these as binary files and it would be a better experience if we imported them as google docs and shared the link.

**Comment by rkelson** [comment]
imported .doc into agrc_public_share/long_term_share/elevation

https://docs.google.com/document/d/1a64Y5lYHYUc4nHcaGUdzHVsLSPGGIxoqhNSiwWdAMpI/edit?usp=sharing
