### ISSUE TITLE
dark mode cards style (purple on purple)

### ISSUE THREAD

**Issue by stdavis** [agrc/gis.utah.gov#2585]
update you  might also like cards to be able to have a different color background when their section has the purple background

![Image](https://github.com/agrc/gis.utah.gov/assets/325813/52017c8c-aab2-41c6-9fc3-b816066b543b)

![Image](https://github.com/agrc/gis.utah.gov/assets/325813/0e8e4443-c191-4a01-8499-fd20a9f85a25)

**Comment by stdavis** [comment]
@steveoh This looks like it's already fixed to me. Can you confirm?


![Image](https://github.com/agrc/gis.utah.gov/assets/1326248/6b3917f4-24f6-443c-9922-e30c206e404d)

**Comment by steveoh** [comment]
Yah I think I got it
