### ISSUE TITLE
Formatting on About page

### ISSUE THREAD

**Issue by jpechmann** [agrc/gis.utah.gov#260]
Change formatting on: https://gis.utah.gov/about/.
- [x] Add link to contributing content
- [ ] make an "about this website" section
- [ ] Create anchor tags
- [ ] Create better subheaders

**Comment by steveoh** [comment]
Where do you want anchor tags and what for? What would be better subheaders?

**Comment by jpechmann** [comment]
I think the anchor tags and subheaders could be combined into creating a better table of contents.

**Comment by steveoh** [comment]
can you give me something that I can act on or is this still in planning? Maybe draw a picture or something.

**Comment by steveoh** [comment]
Can this be closed?

**Comment by jpechmann** [comment]
Sure.
