### ISSUE TITLE
base map api call causing error

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#2628]
browsing to a category index page, in this situation http://localhost:4321/products/sgid/cadastre, caused the error below

<img width="543" alt="image" src="https://github.com/agrc/gis.utah.gov/assets/325813/93236578-bd16-4251-a8ad-b075d5ac8f1b">

The stack trace included this

```
    at async eval (/dev/gis.utah.gov/src/utilities/base-maps-dates.ts:20:1)
```

**Comment by stdavis** [comment]
Closed by https://github.com/agrc/gis.utah.gov/pull/2629
