### ISSUE TITLE
SGID Index reference

### ISSUE THREAD

**Issue by nathankota** [agrc/gis.utah.gov#2685]
Primarily for UGRC staff edification and reference, provide a data model and documentation of the [SGID Index](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1024261148) for an understanding of the fields, how they affect the website, and potential future possibilities of how the index can influence a larger data integration, unification, and automation paradigm and process ("MATT").

**Comment by steveoh** [comment]
https://stackoverflowteams.com/c/ugrc/questions/162
