### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by brigsz** [agrc/gis.utah.gov#2708]
![spellingSteve](https://github.com/agrc/gis.utah.gov/assets/6306463/850d4e26-d4d3-416e-9477-35be16e1afc3)
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having - Collaboration is spelled incorrectly

#### What page is the problem visible
http://gis.utah.gov/

https://gis.utah.gov/blog/2024-03-25-version-7-of-the-ugrc-website-is-here/

#### Expected result
I expected:

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
fixed
