### ISSUE TITLE
SGID Index Validator workflow hitting rate limits

### ISSUE THREAD

**Issue by stdavis** [agrc/gis.utah.gov#2751]
The scheduled runs for the sgid index validation workflow are consistently hitting secondary rate limits when an existing issue is open:
<img width="950" alt="image" src="https://github.com/agrc/gis.utah.gov/assets/1326248/a696aaac-d75d-41bb-afa6-a9d365d1634c">

Here's a similar issue from the action that is causing the issue: https://github.com/JasonEtco/create-an-issue/issues/142

Perhaps we need to roll our own step using actions/github-script?

The manual runs of the workflow seem to run without any issues.

**Comment by steveoh** [comment]
Did you try changing the time of the scheduled run or the token the api request is coming from? Could it use the ugrc app creds?

**Comment by steveoh** [comment]
closed by #2759

**Comment by stdavis** [comment]
Hopefully. 🤞 We won't know for sure until it has run as a scheduled task for a few nights.

**Comment by stdavis** [comment]
It ran successfully last night. Hopefully, that's the end of the rate limit issues.
