### ISSUE TITLE
The SGID Index validation script is hitting GCP rate limits

### ISSUE THREAD

**Issue by stdavis** [agrc/gis.utah.gov#2834]
The issue is that most of the rows are being saved even though only a few have actual edits:

`updated 507 rows` (from a [recent log](https://github.com/agrc/gis.utah.gov/actions/runs/10463470558/job/28975526777))

The check functions need to be debugged to figure out which one is returning a false positive for changed.

@steveoh [added a temporary fix](https://github.com/agrc/gis.utah.gov/compare/72e4c3c134ee36f4892d8aa4c01ddc0c74ac6e1e...main)

**Comment by steveoh** [comment]
I think I have an idea of what is happening here. All of the contact chips `@name` stuff in the contact fields are being replaced with basic text. I think that is why all of these rows are updating. Or at least its a side effect that needs to be addressed since all of the chips are missing.

**Comment by stdavis** [comment]
This issue seems like it's been resolved. I checked the past several runs and all have zero rows updated.

![image](https://github.com/user-attachments/assets/c9519aac-f682-41c5-bd80-b6f3e9287814)

**Comment by steveoh** [comment]
The root cause was 'undefined' === ''
