### ISSUE TITLE
dead link to 2020 census block data

### ISSUE THREAD

**Issue by kemagargal** [agrc/gis.utah.gov#2850]
Hello,

I noticed this morning that the link to download 2020 Census Block Data is broken. The link is the first one under "Explore and Download" at this page: https://gis.utah.gov/products/sgid/demographic/census-2020-blocks/

Thank you.

k

**Comment by stdavis** [comment]
@kemagargal I've got that link fixed. Thanks for letting us know about it! Please let us know if you see any more issues.

**Comment by steveoh** [comment]
Sorry I left this broken to help our esri support case trying to figure out why this keeps happening. There is one other that this happened to that wasn't fixed yet unless you got to that also.

**Comment by stdavis** [comment]
I did fix the other one that we owned. There is one from DNR that I couldn't fix.
