### ISSUE TITLE
✍️ DWMRC Blog Post

### ISSUE THREAD

**Issue by miriamseely** [agrc/gis.utah.gov#2860]
### Blog author

Miriam Seely

### Blog title

DWMRC and UGRC Release Map to Help Utahns Recycle Better

### Blog description

Like love, hope, and cockroaches, trash never truly vanishes. Learn more about how UGRC is collaborating with other agencies to improve waste management practices in Utah.

### Blog category

Collaboration

###

**Comment by steveoh** [comment]
This is an awesome blog post idea. Let me know if you need any help with the tech aspects of writing this!
