### ISSUE TITLE
Update maps on the hill callout with link

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#297]
## Issue description
Describe the problem you are having

I got an email about maps on the hill registration and we should have a link to it on our page.

#### What page is the problem visible
http://gis.utah.gov/

#### Expected result
I expected:

A link to MOTH registration

#### Actual result
Instead:

we still have a save the date

**Comment by jpechmann** [comment]
@steveoh Done! I don't think I can close this, can I?
