### ISSUE TITLE
exposed html

### ISSUE THREAD

**Issue by brigsz** [agrc/gis.utah.gov#303]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having
I see [/tab] and [tab title="Links | Download"]

#### What page is the problem visible
http://gis.utah.gov/

https://gis.utah.gov/data/environment/drinking-water-sytems-protection-zones/

#### Expected result
I expected:
 just clean page, no exposed HTML

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_
![image](https://cloud.githubusercontent.com/assets/6306463/21030103/07e37a54-bd5a-11e6-993c-632c5b78ac05.png)

**Comment by steveoh** [comment]
Do you want to remove these old relics from word press @brigsz? It would be a find and remove. It's not html so it wouldn't mess up anything. It'd be a good pull request for ya!
