### ISSUE TITLE
Links for BLM maps broken

### ISSUE THREAD

**Issue by seanferons** [agrc/gis.utah.gov#442]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having

#### What page is the problem visible
At this url: https://gis.utah.gov/blm-utah-offers-new-recreation-maps-for-mobile-devices/
There are a couple of links for this url:  http://bit.ly/geoPDFutah
But http://bit.ly/geoPDFutah results in a page not found error.

![image](https://cloud.githubusercontent.com/assets/3966308/25136908/7f84142c-2413-11e7-8170-c2b124ef191f.png)

#### Expected result
I expected:

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
Hi and thank you for the issue. Would you please let us know on which page the links are broken? That will help us fix the issue much quicker!

**Comment by jpechmann** [comment]
I am working with the author(s) of this blog at the BLM to get corrected links.

**Comment by steveoh** [comment]
@seanferons I am unsure how familiar you are with github, but @jpechmann created a pull request with new links from the BLM. That page is now updated with the correct links. 

Thank you for the issue!
