### ISSUE TITLE
Missing file for Locators and data pointing to unreachable location

### ISSUE THREAD

**Issue by alantsmith86** [agrc/gis.utah.gov#445]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Hi, I'm trying to download your address locator to use in a school project. When I attempt to download the specific file "Locator_RoadsZip_COMPOSITE.zip" I get a "Network Error" (which doesn't happen on any other file I've tried. I've also tried the link at the top of the page but when attempting to Geocode Addresses with this file it is causing my ArcGIS to stall/error out.

#### What page is the problem visible
https://gis.utah.gov/data/address-geocoders-locators/

#### Expected result
I was hoping for a new upload of these files so I might attempt to finish my project

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
Thanks for the issue! :sparkles: 

I'm sorry about the locators. In the mean time we do have other ways to geocode. Check out api.mapserv.utah.gov.

**Comment by alantsmith86** [comment]
Thank you so much for the swift response! I was biting my nails wondering
if I'd have a solution before the weekend. Thank you thank you have a great
weekend!

**Comment by steveoh** [comment]
If you have esri software you can download or roads and make locators as well but we will get this fixed.

**Comment by stdavis** [comment]
Hey @alantsmith86: We are in the process of fixing those download links. However, those locators reference the SGID SDE database directly. So unless you are inside the State of Utah network they likely won't work. To make them work, you would have to download the reference data (roads, address points) and repoint/rebuild the locators.

I would recommend that you take a look at the tool on this page: https://gis.utah.gov/new-utah-geocoding-toolbox-for-arcgis-desktop-2/. It is targeted for users outside of the state network and uses the web service that @steveoh mentions above (api.mapserv.utah.gov) which is much better than the locators. You'll need to register for an API key to use it. It should be fairly painless. If you have any troubles you are welcome to contact me directly at stdavis@utah.gov. I'll be online all day today until around 5 PM.

Thanks, again for letting us know about the links. I'll keep this issue open until they are fixed.

**Comment by alantsmith86** [comment]
You guys are incredibly helpful. I am a student and just blindly feeling my
way through all of this. Thank you both so much for taking the time to help
me with this and pointing me in the right direction. I will try what you've
suggested!

Thank you
Alan T Smith

**Comment by stdavis** [comment]
I verified that the links to the FTP site for the locators are working now.

**Comment by alantsmith86** [comment]
👍
