### ISSUE TITLE
reorganize discover information/pages

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#476]
We are in the process of making a dedicated landing page for discover. The following is an inventory of the discover information fragments. Let's merge what should be merged into the main page while possibly creating new pages with more in depth information. We can create new urls as long as we redirect the current urls. 

##### should get people the basic information to get started with links to deeper knowledge
https://gis.utah.gov/discover/

### Valuable info page 	
https://gis.utah.gov/data/googleimagery/ 

### Old Signup page for Google with background and archives of links
https://gis.utah.gov/data/google-imagery-license/
	
### Old Signup page for Google with background
https://gis.utah.gov/data/google-imagery-license-signup/
	
### Using SGID base maps & Imagery Services
https://gis.utah.gov/data/base-map-and-imagery/
	
### Using SGID base maps & Imagery Services in Arc
https://gis.utah.gov/data/sgid-base-map-services-arcmap/

### TODO
- [ ] update any outdated information in blog posts

**Comment by rkelson** [comment]
Lots of blog posts. Not sure how best or where to convert the google references into discover references. For starters below is a list of all Google and Discover blog posts.

New 2016 Google imagery
https://gis.utah.gov/new-2016-google-imagery/

Google speed enhancements
https://gis.utah.gov/google-imagery-service-speed-enhancements-more/

Google update July 15
https://gis.utah.gov/google-imagery-update-july-2015/

Google: wms and wmts
https://gis.utah.gov/google-imagery-wms-and-wmts-imagery-services/

Using Utah's Google imagery License
https://gis.utah.gov/google-imagery-license-update-march-5th/

Tracking Server Response times
https://gis.utah.gov/tracking-server-response-times-with-the-google-spreadsheets-api-and-asp-net/

New discover services
https://gis.utah.gov/new-services-on-discover/

Printing WEb maps with disco
https://gis.utah.gov/printing-web-maps-with-discover-services/

**Comment by steveoh** [comment]
I think most we can leave as is, but some we should 

### 
- https://gis.utah.gov/new-2016-google-imagery/ - This is not important anymore and could possibly be removed. The sign up link will redirect to the new location. But we could update it if we decide to keep it. I will let you decide. 
- https://gis.utah.gov/google-imagery-service-speed-enhancements-more/ - you tell me what to do with this one. It seems like it has information that isn't pertinent anymore but it also seems like benign information that doesn't affect anything we are planning to do. 
- https://gis.utah.gov/google-imagery-update-july-2015/ - this one seems like the one above. It might have some misleading information and links to places we aren't maintaining anymore so it should probably be updated.
- https://gis.utah.gov/google-imagery-wms-and-wmts-imagery-services/ - this page seems fine. Maybe we will update the link to the google imagery page.
- https://gis.utah.gov/google-imagery-license-update-march-5th/ - this one seems fine. Is the organization usage agreement link current? 
- https://gis.utah.gov/tracking-server-response-times-with-the-google-spreadsheets-api-and-asp-net/ - this is unrelated and we can ignore it.
- https://gis.utah.gov/new-services-on-discover/ - we might need to update the link in the bottom but a historical view at when things happened is a good thing I think.
- https://gis.utah.gov/printing-web-maps-with-discover-services/ - we can ignore this one as well but we should probably link to it from the new discover page somewhere.

**Comment by rkelson** [comment]
so something like this at the top of all the post?

<div class="grid pop">
    <div class="grid__col grid__col--1-of-2">
        <p>This is an old blog post. For the most recent information visit the [Discover]({{ "/discover/" | prepend: site.baseurl }}) page.</p>
    </div>

**Comment by steveoh** [comment]
I would say something like, `the data on this page could be outdated. For the most recent...`

**Comment by steveoh** [comment]
I set up redirects and updated the [folder structure](https://github.com/agrc/gis.utah.gov/tree/master/discover) for discover. Give it a look when you have time and let me know if you have any issues with it.

**Comment by rkelson** [comment]
I took a look and things look great

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov
