### ISSUE TITLE
broken link on https://gis.utah.gov/data/demographic/2010-census-data/

### ISSUE THREAD

**Issue by annearendt** [agrc/gis.utah.gov#488]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having
Link broken on https://gis.utah.gov/data/demographic/2010-census-data/ where it says  http://www.datafinder.org/metadata/Census2010Tiger.html 

#### What page is the problem visible
https://gis.utah.gov/data/demographic/2010-census-data/

#### Expected result
I expected:

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
Thank you @annearendt. We will look to see where the link to that census data is now. Thank you for the heads up! ✨
