### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ccassle** [agrc/gis.utah.gov#497]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having

I am trying to download shapefiles from the following sites and none of the links work. I have tried downloading several different data packages and literally none of the links on the gis.utah.gov site work. 

https://gis.utah.gov/data/energy/oil-gas/
https://gis.utah.gov/data/sgid-cadastre/plss/
https://gis.utah.gov/data/sgid-cadastre/

#### What page is the problem visible
http://gis.utah.gov/

https://gis.utah.gov/data/energy/oil-gas/
https://gis.utah.gov/data/sgid-cadastre/plss/
https://gis.utah.gov/data/sgid-cadastre/

#### Expected result
I expected:

to be able to download the data

#### Actual result
Instead:
the following error:

Hmmm...can’t reach this page
Try this
Make sure you’ve got the right web address: ftp://ftp.agrc.utah.gov
Search for "ftp://ftp.agrc.utah.gov" on Bing
Refresh the page

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
I was able to download all of the resources from the oil and gas page that you linked from within and outside of the state network. That makes me think our site and network are not having issues.

The problem might be with your browser configuration or some company firewall settings?

Are you on a private or corporate network? 
What browser and version are you currently using? Can you try other browsers and see if you get the same result?

Thanks

**Comment by ccassle** [comment]
Hi,

Good call on switching browsers! Everything worked perfectly when I switched to google chrome.

Thank you!

**Comment by steveoh** [comment]
🚀
