### ISSUE TITLE
Bad links on https://gis.utah.gov/data/environment/deq-land-related-contaminant-cleanup-sites/

### ISSUE THREAD

**Issue by mheagin** [agrc/gis.utah.gov#498]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
User couldn't download data for Environment.DSHWPermittedUsedOilFacilities. 
Seems like this data is no longer available. Nothing in SGID Index table, ftp site, or SGID10.sde 

#### What page is the problem visible
https://gis.utah.gov/data/environment/deq-land-related-contaminant-cleanup-sites/

ftp://ftp.agrc.utah.gov/UtahSGID_Vector/UTM12_NAD83/ENVIRONMENT/UnpackagedData/DSHWPermittedUsedOilFacilities/_Statewide/DSHWPermittedUsedOilFacilities_gdb.zip

#### Expected result
Page needs to be adjusted to remove this data info and maybe others. 
Not sure who works with DEQ on their data these days, Matt gave me information on there new web app/page if that is a replacement link we want to add: https://enviro.deq.utah.gov/

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by stdavis** [comment]
I can take a look at this...

**Comment by stdavis** [comment]
@ZachBeck is taking a look at this. Looks like we have differences between this page, SDE and the [ftp packages that are built in the deq pallet](https://github.com/agrc/deq-enviro/blob/master/scripts/nightly/update_ftp.py#L7-L50).
