### ISSUE TITLE
1 Page per Day

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#515]
Fix the markup and look over one page per day line by line to ensure that these pages are good. 

Stuff to check:

### Posts/Pages
- add/remove good and bad tags
- read page and fix errors in text
- validate/beautify html
- switch package to use 
```ruby
{% include abstract.html download=url
  name=package name
  type=default:GIS Data Layer
  stewards=default:AGRC
  webapp=link
  abstract=abstract %}
```
   - **you need to quote yaml characters like `:` if they are in the string**
- switch downloads updates to use front matter 
```yml
---
PackageNameFromH3Id:
  downloads:
    - url: url
      label: a href value
    - url: url2
      label: a href value
  updates:
    - most recent
    - older ones
---
```
```ruby
{% include packagedata.hml name="layer"
   info=page.PackageNameFromH3Id %}
```
- move `other links` from the download tab to the panel content `h5 ul.dotless` (remove `productLink` classes)
- look for generic alt tags (e.g. `alt="Changeme"`)
- all text should be in `p` tags.

### Overview Pages
- remove `-overview` and `sgid-` from page name and update links and `_redirects` and the [stewardship spreadsheet](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1)
- add `overview` tag
- update class to text center on opening `h6` and remove other garbage
- update width on product and description to 25% and 40%
- remove all inline styles
- remove empty headings at bottom
- update used headings to `h4` and `ul.dotless`

### Honeydos
 - [x] [location/gnis](https://gis.utah.gov/data/location/gnis/)
 - [x] [society-overview/public-safety](https://gis.utah.gov/data/society-overview/public-safety/)
 - [x] [society-overview](https://gis.utah.gov/data/society-overview/)
 - [x] ~[land-ownership-stewardship-designation](https://gis.utah.gov/data/land-ownership-stewardship-designation/)~
 - [x] [environment/drinking-water-sytems-protection-zones](https://gis.utah.gov/data/environment/drinking-water-sytems-protection-zones/)
 - [x] [environment/deq-air-related-contaminant-cleanup-sites](https://gis.utah.gov/data/environment/deq-air-related-contaminant-cleanup-sites/)
 - [x] [environment/deq-land-related-contaminant-cleanup-sites](https://gis.utah.gov/data/environment/deq-land-related-contaminant-cleanup-sites/)
 - [x] [environment](https://gis.utah.gov/data/environment/)
 - [x] ~[farming/grazing-improvement-area](https://gis.utah.gov/data/farming/grazing-improvement-area/)~
 - [x] [farming/grazing-improvements](https://gis.utah.gov/data/farming/grazing-improvements/)
 - [x] ~[farming/grazing-allotments](https://gis.utah.gov/data/farming/grazing-allotments/)~
 - [x] [farming](https://gis.utah.gov/data/farming/)
 - [x] [address-overview/address-grids/notes-utah-local-addressing-systems-address-grids](https://gis.utah.gov/data/address-overview/address-grids/notes-utah-local-addressing-systems-address-grids/)
 - [x] [address-overview](https://gis.utah.gov/data/address-overview/)
 - [x] [sgid-indices/auto-correlated-dem-indices](https://gis.utah.gov/data/sgid-indices/auto-correlated-dem-indices/)
 - [x] [sgid-indices/contours-indices](https://gis.utah.gov/data/sgid-indices/contours-indices/)
 - [x] [sgid-indices/usgs-dem-indices](https://gis.utah.gov/data/sgid-indices/usgs-dem-indices/)
 - [x] [sgid-indices/lidar-indices](https://gis.utah.gov/data/sgid-indices/lidar-indices/)
 - [x] [sgid-indices/aerial-photography-indices](https://gis.utah.gov/data/sgid-indices/aerial-photography-indices/)
 - [x] [sgid-indices/usgs-topo-indices](https://gis.utah.gov/data/sgid-indices/usgs-topo-indices/)
 - [x] [sgid-indices/national-grid-index](https://gis.utah.gov/data/sgid-indices/national-grid-index/)
 - [x] [sgid-indices](https://gis.utah.gov/data/sgid-indices/)
 - [x] [usgs-scanned-topographic-maps-drgs/quad-name-usgs-scanned-topographic-maps-1250000-geotiff](https://gis.utah.gov/data/usgs-scanned-topographic-maps-drgs/quad-name-usgs-scanned-topographic-maps-1250000-geotiff/)
 - [x] [usgs-scanned-topographic-maps-drgs/quad-name-usgs-scanned-topographic-maps-1100000-geotiff](https://gis.utah.gov/data/usgs-scanned-topographic-maps-drgs/quad-name-usgs-scanned-topographic-maps-1100000-geotiff/)
 - [x] [usgs-scanned-topographic-maps-drgs/vintage-usgs-topo-maps](https://gis.utah.gov/data/usgs-scanned-topographic-maps-drgs/vintage-usgs-topo-maps/)
 - [x] [usgs-scanned-topographic-maps-drgs/quad-number-usgs-scanned-topographic-maps-1100000-geotiff](https://gis.utah.gov/data/usgs-scanned-topographic-maps-drgs/quad-number-usgs-scanned-topographic-maps-1100000-geotiff/)
 - [x] [usgs-scanned-topographic-maps-drgs/quad-number-usgs-scanned-topographic-maps-124000-geotiff](https://gis.utah.gov/data/usgs-scanned-topographic-maps-drgs/quad-number-usgs-scanned-topographic-maps-124000-geotiff/)
 - [x] [usgs-scanned-topographic-maps-drgs/quad-name-usgs-scanned-topographic-maps-124000-geotiff-2](https://gis.utah.gov/data/usgs-scanned-topographic-maps-drgs/quad-name-usgs-scanned-topographic-maps-124000-geotiff-2/)
 - [x] [usgs-scanned-topographic-maps-drgs/quad-number-usgs-scanned-topographic-maps-1250000-geotiff](https://gis.utah.gov/data/usgs-scanned-topographic-maps-drgs/quad-number-usgs-scanned-topographic-maps-1250000-geotiff/)
 - [x] [usgs-scanned-topographic-maps-drgs](https://gis.utah.gov/data/usgs-scanned-topographic-maps-drgs/)
 - [x] [economy/taxingareas](https://gis.utah.gov/data/economy/taxingareas/)
 - [x] [economy/enterprise-zones](https://gis.utah.gov/data/economy/enterprise-zones/)
 - [x] [economy](https://gis.utah.gov/data/economy/)
 - [x] [society-overview/liquor-stores](https://gis.utah.gov/data/society-overview/liquor-stores/)
 - [x] [health/emergency-regions](https://gis.utah.gov/data/health/emergency-regions/)
 - [x] [health/health-care-facilities](https://gis.utah.gov/data/health/health-care-facilities/)
 - [x] [health/health-districts](https://gis.utah.gov/data/health/health-districts/)
 - [x] [health/emergency-service-areas](https://gis.utah.gov/data/health/emergency-service-areas/)
 - [x] [health/health-small-statistical-areas](https://gis.utah.gov/data/health/health-small-statistical-areas/)
 - [x] [health](https://gis.utah.gov/data/health/)
 - [x] [sgid-disclaimer](https://gis.utah.gov/data/sgid-disclaimer/)
 - [x] [society-overview/state-facilities](https://gis.utah.gov/data/society-overview/state-facilities/)
 - [x] [society-overview/schools-libraries](https://gis.utah.gov/data/society-overview/schools-libraries/)
 - [x] [planning/water-related-land](https://gis.utah.gov/data/planning/water-related-land/)
 - [x] [planning](https://gis.utah.gov/data/planning/)
 - [x] [sgid-blog](https://gis.utah.gov/data/sgid-blog/)
 - [x] [sgid-water-data](https://gis.utah.gov/data/sgid-water-data/)
 - [x] [history](https://gis.utah.gov/data/history/)
 - [x] [society-overview/blm-field-offices-forest-service-stations](https://gis.utah.gov/data/society-overview/blm-field-offices-forest-service-stations/)
 - [x] [sgid-imagery-services](https://gis.utah.gov/data/sgid-imagery-services/)
 - [x] [geoscience/soil](https://gis.utah.gov/data/geoscience/soil/)
 - [x] [geoscience/quaternary-faults](https://gis.utah.gov/data/geoscience/quaternary-faults/)
 - [x] [geoscience/avalanche](https://gis.utah.gov/data/geoscience/avalanche/)
 - [x] [geoscience/aquifers-2](https://gis.utah.gov/data/geoscience/aquifers-2/)
 - [x] [geoscience](https://gis.utah.gov/data/geoscience/)
 - [x] [water-data-services/water-rights-regions](https://gis.utah.gov/data/water-data-services/water-rights-regions/)
 - [x] [water-data-services/wetlands](https://gis.utah.gov/data/water-data-services/wetlands/)
 - [x] [water-data-services/lakes-rivers-dams](https://gis.utah.gov/data/water-data-services/lakes-rivers-dams/)
 - [x] [water-data-services/historic-lake-bonneville](https://gis.utah.gov/data/water-data-services/historic-lake-bonneville/)
 - [x] [water-data-services/watersheds](https://gis.utah.gov/data/water-data-services/watersheds/)
 - [x] [water-data-services/flood-areas](https://gis.utah.gov/data/water-data-services/flood-areas/)
 - [x] [water-data-services](https://gis.utah.gov/data/water-data-services/)
 - [x] [utilities/retail-culinary-water-suppliers](https://gis.utah.gov/data/utilities/retail-culinary-water-suppliers/)
 - [x] [utilities/telephone-infrastructure-and-rural-telcom-boundaries](https://gis.utah.gov/data/utilities/telephone-infrastructure-and-rural-telcom-boundaries/)
 - [x] [utilities/broadband-internet](https://gis.utah.gov/data/utilities/broadband-internet/)
 - [x] [utilities](https://gis.utah.gov/data/utilities/)
 - [x] ~[elevation-terrain-data/5-meter-auto-correlated-elevation-models](https://gis.utah.gov/data/elevation-terrain-data/5-meter-auto-correlated-elevation-models/)~
 - [x] [elevation-terrain-data/exploring-lidar](https://gis.utah.gov/data/elevation-terrain-data/exploring-lidar/)
 - [x] ~[elevation-terrain-data/2-meter-auto-correlated-elevation-models](https://gis.utah.gov/data/elevation-terrain-data/2-meter-auto-correlated-elevation-models/)~
 - [x] ~[elevation-terrain-data/500-foot-contours](https://gis.utah.gov/data/elevation-terrain-data/500-foot-contours/)~
 - [x] [elevation-terrain-data/contours](https://gis.utah.gov/data/elevation-terrain-data/contours/)
 - [x] [elevation-terrain-data/2-meter-lidar](https://gis.utah.gov/data/elevation-terrain-data/2-meter-lidar/)
 - [x] [elevation-terrain-data/2013-2014-lidar](https://gis.utah.gov/data/elevation-terrain-data/2013-2014-lidar/)
 - [x] ~[elevation-terrain-data/10-30-meter-elevation-models-usgs-ned](https://gis.utah.gov/data/elevation-terrain-data/10-30-meter-elevation-models-usgs-ned/)~
 - [x] ~[elevation-terrain-data/10-30-90-meter-elevation-models-usgs-dems](https://gis.utah.gov/data/elevation-terrain-data/10-30-90-meter-elevation-models-usgs-dems/)~
 - [x] [elevation-terrain-data/2011-lidar](https://gis.utah.gov/data/elevation-terrain-data/2011-lidar/)
 - [x] ~[elevation-terrain-data/2-meter-contours-salt-lake-county-only](https://gis.utah.gov/data/elevation-terrain-data/2-meter-contours-salt-lake-county-only/)~
 - [x] ~[elevation-terrain-data/sgid-elevation-terrain-data-overview-utah](https://gis.utah.gov/data/elevation-terrain-data/sgid-elevation-terrain-data-overview-utah/)~
 - [x] [elevation-terrain-data](https://gis.utah.gov/data/elevation-terrain-data/)
 - [x] [recreation/boat-ramps](https://gis.utah.gov/data/recreation/boat-ramps/)
 - [x] [recreation/golf-courses](https://gis.utah.gov/data/recreation/golf-courses/)
 - [x] [recreation/local-parks](https://gis.utah.gov/data/recreation/local-parks/)
 - [x] [recreation/ski-areas](https://gis.utah.gov/data/recreation/ski-areas/)
 - [x] [recreation/urban-trails](https://gis.utah.gov/data/recreation/urban-trails/)
 - [x] [recreation/trails](https://gis.utah.gov/data/recreation/trails/)
 - [x] [recreation](https://gis.utah.gov/data/recreation/)
 - [x] [connecting-sgid-arcsde-server](https://gis.utah.gov/data/connecting-sgid-arcsde-server/)
 - [x] [boundaries/conservation-districts](https://gis.utah.gov/data/boundaries/conservation-districts/)
 - [x] [boundaries/school-districts](https://gis.utah.gov/data/boundaries/school-districts/)
 - [x] [boundaries/wilderness](https://gis.utah.gov/data/boundaries/wilderness/)
 - [x] [boundaries/zip-codes](https://gis.utah.gov/data/boundaries/zip-codes/)
 - [x] [boundaries/citycountystate](https://gis.utah.gov/data/boundaries/citycountystate/)
 - [x] [boundaries](https://gis.utah.gov/data/boundaries/)
 - [x] [aerial-photography/2003-1-meter-color-doqs-beaver-iron-only](https://gis.utah.gov/data/aerial-photography/2003-1-meter-color-doqs-beaver-iron-only/)
 - [x] [aerial-photography/2006-naip-1-meter-color-orthophotography](https://gis.utah.gov/data/aerial-photography/2006-naip-1-meter-color-orthophotography/)
 - [x] [aerial-photography/2003-uao-1-foot-color-orthophotography](https://gis.utah.gov/data/aerial-photography/2003-uao-1-foot-color-orthophotography/)
 - [x] [aerial-photography/2009-hro-1-foot-color-orthophotography](https://gis.utah.gov/data/aerial-photography/2009-hro-1-foot-color-orthophotography/)
 - [x] [aerial-photography/1977-1-meter-black-white-doqs-salt-lake-county-only](https://gis.utah.gov/data/aerial-photography/1977-1-meter-black-white-doqs-salt-lake-county-only/)
 - [x] [aerial-photography/2012-hro-6-inch-color-orthophotography](https://gis.utah.gov/data/aerial-photography/2012-hro-6-inch-color-orthophotography/)
 - [x] [aerial-photography/2014-naip-1-meter-orthophotography](https://gis.utah.gov/data/aerial-photography/2014-naip-1-meter-orthophotography/)
 - [x] [aerial-photography/mid-1990s-1-meter-black-white-orthophotography](https://gis.utah.gov/data/aerial-photography/mid-1990s-1-meter-black-white-orthophotography/)
 - [x] [aerial-photography/2006-hro-1-foot-color-orthophotography](https://gis.utah.gov/data/aerial-photography/2006-hro-1-foot-color-orthophotography/)
 - [x] [aerial-photography/imagery-problems](https://gis.utah.gov/data/aerial-photography/imagery-problems/)
 - [x] [aerial-photography/2016-naip-1-meter-orthophotography](https://gis.utah.gov/data/aerial-photography/2016-naip-1-meter-orthophotography/)
 - [x] [aerial-photography/2011-naip-1-meter-orthophotography](https://gis.utah.gov/data/aerial-photography/2011-naip-1-meter-orthophotography/)
 - [x] [aerial-photography/2009-naip-1-meter-orthophotography](https://gis.utah.gov/data/aerial-photography/2009-naip-1-meter-orthophotography/)
 - [x] [aerial-photography](https://gis.utah.gov/data/aerial-photography/)
 - [x] [energy/oil-gas](https://gis.utah.gov/data/energy/oil-gas/)
 - [x] [energy/uranium](https://gis.utah.gov/data/energy/uranium/)
 - [x] [energy/coal](https://gis.utah.gov/data/energy/coal/)
 - [x] [energy/renewable-energy](https://gis.utah.gov/data/energy/renewable-energy/)
 - [x] [energy/energy-generation](https://gis.utah.gov/data/energy/energy-generation/)
 - [x] [society/state-fuel-sites](https://gis.utah.gov/data/society/state-fuel-sites/)
 - [x] [energy](https://gis.utah.gov/data/energy/)
 - [x] [sgid-cadastre/land-ownership](https://gis.utah.gov/data/sgid-cadastre/land-ownership/)
 - [x] [sgid-cadastre/turn-gps](https://gis.utah.gov/data/sgid-cadastre/turn-gps/)
 - [x] [sgid-cadastre/plss](https://gis.utah.gov/data/sgid-cadastre/plss/)
 - [x] [sgid-cadastre/parcels](https://gis.utah.gov/data/sgid-cadastre/parcels/)
 - [x] [sgid-cadastre](https://gis.utah.gov/data/sgid-cadastre/)
 - [x] [society-overview/places-of-worship](https://gis.utah.gov/data/society-overview/places-of-worship/)
 - [x] [location/place-areas](https://gis.utah.gov/data/location/place-areas/)
 - [x] [location/building-footprint](https://gis.utah.gov/data/location/building-footprint/)
 - [x] [location/u-s-postal-service](https://gis.utah.gov/data/location/u-s-postal-service/)
 - [x] [location/address-data](https://gis.utah.gov/data/location/address-data/)
 - [x] [location](https://gis.utah.gov/data/location/)
 - [x] [demographic/2000-census-data](https://gis.utah.gov/data/demographic/2000-census-data/)
 - [x] [demographic/2010-census-data](https://gis.utah.gov/data/demographic/2010-census-data/)
 - [x] [demographic](https://gis.utah.gov/data/demographic/)
 - [x] [climate](https://gis.utah.gov/data/climate/)
 - [x] [undreground-storage-tanks](https://gis.utah.gov/data/undreground-storage-tanks/)
 - [x] [how-to-connect-to-the-sgid-via-sde](https://gis.utah.gov/data/how-to-connect-to-the-sgid-via-sde/)
 - [x] [political/2012-2021-house-senate-congressional-districts](https://gis.utah.gov/data/political/2012-2021-house-senate-congressional-districts/)
 - [x] [political/judicial-districts](https://gis.utah.gov/data/political/judicial-districts/)
 - [x] [political/voter-precincts](https://gis.utah.gov/data/political/voter-precincts/)
 - [x] [political/2002-2011-house-senate-congressional-districts](https://gis.utah.gov/data/political/2002-2011-house-senate-congressional-districts/)
 - [x] [political](https://gis.utah.gov/data/political/)
 - [x] [society-overview/cemeteries](https://gis.utah.gov/data/society-overview/cemeteries/)
 - [x] [transportation/roads-system](https://gis.utah.gov/data/sgid-transportation/roads-system/)
 - [x] [transportation/street-network-analysis](https://gis.utah.gov/data/sgid-transportation/street-network-analysis/)
 - [x] [transportation/railroads](https://gis.utah.gov/data/sgid-transportation/railroads/)
 - [x] [transportation/transit](https://gis.utah.gov/data/sgid-transportation/transit/)
 - [x] [transportation](https://gis.utah.gov/data/sgid-transportation/)
 - [x] [address-geocoders-locators](https://gis.utah.gov/data/address-geocoders-locators/)
 - [x] ~[bioscience-overview/dominant-vegetation](https://gis.utah.gov/data/bioscience-overview/dominant-vegetation/)~
 - [x] [bioscience-overview/department-wildlife-resources-habitat-areas](https://gis.utah.gov/data/bioscience-overview/department-wildlife-resources-habitat-areas/)
 - [x] [bioscience-overview](https://gis.utah.gov/data/bioscience-overview/)
 - [x] [transportation/air](https://gis.utah.gov/data/sgid-transportation/air/)
 - [x] [base-map-and-imagery](https://gis.utah.gov/data/base-map-and-imagery/)
 - [x] [aerial-photography/1936-1952-soil-conservation-service-scs-photomaps](https://gis.utah.gov/data/aerial-photography/1936-1952-soil-conservation-service-scs-photomaps/)
 - [x] [discover-server-information](https://gis.utah.gov/data/discover-server-information/)
 - [x] [aerial-photography/1970s-1-meter-blm-orthophotography](https://gis.utah.gov/data/aerial-photography/1970s-1-meter-blm-orthophotography/)
 - [x] [elevation-terrain-data/2016-lidar-monroe-mtn](https://gis.utah.gov/data/elevation-terrain-data/2016-lidar-monroe-mtn/)
 - [x] [google-imagery-license-signup](https://gis.utah.gov/data/google-imagery-license-signup/)
 - [x] [sgid-base-map-services-arcmap](https://gis.utah.gov/data/sgid-base-map-services-arcmap/)
 - [x] [google-imagery-license](https://gis.utah.gov/data/google-imagery-license/)

**Comment by stdavis** [comment]
Want help?

**Comment by steveoh** [comment]
Sure! 🍭 

Do you have enough to go with with the [gnis diff](https://github.com/agrc/gis.utah.gov/commit/b5758ff9e0d22fd44f6d69184d862a8372bb4eb4)?

**Comment by stdavis** [comment]
Is there a list of approved tags somewhere?

I probably need a checklist to go through. Can we add it to the description for this issue?

**Comment by steveoh** [comment]
There is not. There is #8 but nothing moving on it. I would use your own judgement to remove the cruft and add useful tags.

**Comment by stdavis** [comment]
That seems subjective. Maybe it should be done by only one person.

**Comment by steveoh** [comment]
Let's start by removing 


- utah
- gis
- map
- mapping
- dataset
- download
- agrc
- layer
- shapefile
- geodatabase
- metadata
- shp
- gdb
- kml
- lyr
- digital
- geographic
- information
- database
- state
- statewide

since they add 0 value.

**Comment by stdavis** [comment]
I couldn't find anything to change on https://gis.utah.gov/data/google-imagery-license/. No tags because it's a page, not a post? Anything that should be changed from your view?

**Comment by steveoh** [comment]
> I couldn't find anything to change on https://gis.utah.gov/data/google-imagery-license/. No tags because it's a page, not a post? Anything that should be changed from your view?

The markdown ones should be simpler. The html data package pages that were generated and modified by the jekyll and my import process will need a closer inspection. For things like valid html and extraneous markup.

**Comment by stdavis** [comment]
I'm guessing that `statewide` is a pretty useless tag as well?

**Comment by steveoh** [comment]
I am unsure. I left it as there might be data that isn't state wide but yeah, it's probably pretty useless.

**Comment by steveoh** [comment]
I made a script and a pr to fix up the front matter. So don't mess with it until we merge that pr otherwise conflicts.

**Comment by stdavis** [comment]
I'm done with all of the usgs ones. Am I OK to move on to other unchecked pages?

**Comment by steveoh** [comment]
yup. clear to go

**Comment by steveoh** [comment]
I'd like to start removing pages that are not "data" and placing them in more appropriate places. The discover pages that are in data and the connecting to sgid/image server for example should be moved to the discover folder and somewhere else.

**Comment by steveoh** [comment]
![it happened](https://media.giphy.com/media/h8UyZ6FiT0ptC/giphy.gif)
