### ISSUE TITLE
StateFuelSites is now in society

### ISSUE THREAD

**Issue by keatonwalker** [agrc/gis.utah.gov#525]
The [data page for State Fuel Sites](https://github.com/agrc/gis.utah.gov/blob/master/data/energy/state-fuel-sites/index.html) is under energy but the SGID data is under society.

**Comment by steveoh** [comment]
closed with https://github.com/agrc/gis.utah.gov/commit/6ec98c22f0bf02e8f2b28911f4eb81fbdcaba87d
