### ISSUE TITLE
FGDC Metadata

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#596]
It's on the FTP and it's old but is it still relevant?

Since we moved all of the data to drive, what do we do with the links to the FGDC metadata on the FTP?

**Comment by keatonwalker** [comment]
We have new FGDC metadata in ftp/UtahSGID_Vector/UTM12_NAD83/Metadata/ that is actively maintained. It is in xml format rather than html.

**Comment by steveoh** [comment]
That is great news to me! We will need to update some links then. I'm not sure how to convert between them but hopefully it is a find and replace on folder and extension? 

Would you toss a PR at this when you get a chance @keatonwalker?

**Comment by keatonwalker** [comment]
I will. I have some other links to fix at the same time.
