### ISSUE TITLE
Display analytics for page

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#609]
@BGranberg thought it would be cool to show the analytics for the website or current page somewhere in the page.

Research google analytics to see if there is an api or report we can query on each page load.

![really](http://www.gifandgif.eu/animated_gif/Counters/Animated%20Gif%20Counter%20%2811%29.gif)

**Comment by steveoh** [comment]
It looks like it can be done but I don't think it would work how you want. It would require authenticating etc yada yada. Without doing something goofy I don't see a way to make this happen per page in an anonymous way. I'll keep my eyes open though. Maybe @keatonwalker will know some googlefu to work it out.

**Comment by stdavis** [comment]
Maybe you could build a google cloud function and just count simple page views? On each page load send a request to increment the count and get the total. I'd be up for giving this a try.

**Comment by steveoh** [comment]
That is the google fu I was talking about. Go for it!

**Comment by keatonwalker** [comment]
I think the page views in Google Analytics records simple page views in a similar way @stdavis. We might want to first try and get the pageview metric with the analytics api and load that into the page.

**Comment by stdavis** [comment]
@keatonwalker Did you find a way to get google analytics data without having to authenticate? Otherwise, a serverless function might be easier.

**Comment by keatonwalker** [comment]
Here are a few other options:

- It looks like you can use service accounts to access the analytics reporting api. 
- I think you could also export the analytics data and query it. 
- There are also the DataStudio reports that can connect directly to analytics and be embedded by report page. It might be cumbersome to build a report page per counted page, but the analytics connection is easy.
