### ISSUE TITLE
Organize contacts in a manageable area

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#611]
The contacts for stewards and what not change frequently. I think we could use jekyll concepts to organize a list of generic contacts and have jekyll replace all occurrences of them in the website with a simple change. 

We are probably serving emails and phone numbers for outdated or unrelated people.

**Comment by steveoh** [comment]
There are 232 instances of a `mailto:someone` in our website. That seems not ideal. I will try to pull a list.

**Comment by steveoh** [comment]
Here is a list of the folks. @brigsz do any of these stand out as plain wrong at first glance?

```['mailto:jranders@blm.gov', 'mailto:dbuell@utah.gov', 'mailto:katesmith8@gmail.com', 'mailto:sgourley@utah.gov', 'mailto:agrc@utah.gov', 'mailto:gdouglass@utah.gov', 'mailto:david.evans@sgcity.org', 'mailto:leschler@utah.gov', 'mailto:aaronaustin@utah.gov', 'mailto:dbeck@utah.gov', 'mailto:jessicakirby@utah.gov', 'mailto:sfernandez@utah.gov', 'mailto:keatonwalker@utah.gov', 'mailto:jonny.stromberg@gmail.com', 'mailto:michaelfoulger@utah.gov', 'mailto:khansen@jub.com', 'mailto:brooke.conner@fema.dhs.gov', 'mailto:TLA-GIS@utah.gov', 'mailto:zbeck@utah.gov', 'mailto:mpeters@utah.gov', 'mailto:donstaley@utah.gov', 'mailto:rkelson@utah.gov', 'mailto:gbunce@utah.gov', 'mailto:bgranberg@utah.gov', 'mailto:kjohnson@utah.gov', 'mailto:rsempler@utah.gov', 'mailto:tchidester@utah.gov', 'mailto:tschulzke@ufa-slco.org', 'mailto:leeeschler@utah.gov', 'mailto:mheagin@utah.gov', 'mailto:nkenczka@utah.gov', 'mailto:bradhill@utah.gov', 'mailto:mjthomas@utah.gov', 'mailto:lnelms@rideuta.com']```

**Comment by stdavis** [comment]
Might be worth sending an email to that list just to verify that they are good addresses and that the recipients are still valid.

**Comment by steveoh** [comment]
not it!

**Comment by brigsz** [comment]
Yes, there are some that standout as just plain wrong.  How do you want me to edit?

**Comment by steveoh** [comment]
I will create a spreadsheet where we can track some information
