### ISSUE TITLE
Cannot get Geocoder API key 

### ISSUE THREAD

**Issue by XiozTzu** [agrc/gis.utah.gov#614]
## Issue description
Cannot get Geocoder API key because the account set up text box cuts off my email address at 30 characters.  My email address is 35 characters long!

#### What page is the problem visible
 https://developer.mapserv.utah.gov/AccountAccess

#### Expected result
To be able to get an API key.

#### Actual result
I cannot.

**Comment by steveoh** [comment]
I am going to move this to the web api repository. 

https://github.com/agrc/api.mapserv.utah.gov/issues/58

**Comment by steveoh** [comment]
I pushed a fix for this. Give it a shot.

**Comment by XiozTzu** [comment]
Works now. Thank you!
