### ISSUE TITLE
there is an issue with the link to the golf courses data, I will send them a copy can you look for the issue. Thanks https://gis.utah.gov/data/recreation/golf-courses/

### ISSUE THREAD

**Issue by mheagin** [agrc/gis.utah.gov#620]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having
User reported bad link on https://gis.utah.gov/data/recreation/golf-courses/

#### What page is the problem visible
https://gis.utah.gov/data/recreation/golf-courses/

#### Expected result
to be able to download data

#### Actual result

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
my bad. I added an extra character to the link by accident.
