### ISSUE TITLE
Incorrect address...

### ISSUE THREAD

**Issue by d-how** [agrc/gis.utah.gov#623]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having
We have the address 650 S Flora Tech Rd, 84737 and I found the API does not resolve the address correctly. The API returns a not found message. However, it does find 650 S Flora Tec Rd
, 84737 (Tech vs Tec). the street is actually Flora Tech not Flora Tec.

#### What page is the problem visible
http://gis.utah.gov/
API

#### Expected result
I expected:

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
moving this incident to the api repository since this area is for our wesbite. 

Please subscribe to this issue
https://github.com/agrc/api.mapserv.utah.gov/issues/59
