### ISSUE TITLE
Review data packages on all product pages

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#656]
Should all of the items on a product page be included in the packaged download or only some? 

We need to triage all of the data pages and identify what should be combined.

**Comment by brigsz** [comment]
Are there some that you feel are outliers?

**Comment by steveoh** [comment]
There were a few when I went through each page but I didn't write them down. 

I think we need to look at all of the packages. I think @keatonwalker could give us a list from backseat driver. Then we would know if some new packages need to be created or if existing ones need updating.

**Comment by keatonwalker** [comment]
I can create a list of packages and the features in them. Backseat driver doesn't maintain info about which pages contain data and packages but we could get this info other ways.

**Comment by steveoh** [comment]
that would be a great start. thanks @keatonwalker

**Comment by steveoh** [comment]
keep this on your radar @keatonwalker. if you get bored

**Comment by steveoh** [comment]
we're taking a new direction here by removing the package downloads. I'll create another issue to track that progress.
