### ISSUE TITLE
Building footprint data missing?

### ISSUE THREAD

**Issue by CraigglesO** [agrc/gis.utah.gov#672]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having
The building footprint data is sparse in Utah.

#### What page is the problem visible
http://gis.utah.gov/

#### Expected result
I expected:
More data,

#### Actual result
Instead:
There is little building footprint data

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

Parcel data is complete, building data is not. Do you guys have a suggestion here? What government project handles this?

Thanks,
Craig.

**Comment by brigsz** [comment]
Good Morning Craig,

We have not started a formal effort to collect building footprints.  There have been some efforts to derive this info from LiDAR, Some of the more populous have derived the data and you could probably download it from their individual sites.  I am sure as time goes by and LiDAR for the state becomes available it will be a product that will be available statewide.

**Comment by CraigglesO** [comment]
Thanks for the response! Will look into LiDAR :)
