### ISSUE TITLE
UtahMajorRiversPoly shapefile - invalid features

### ISSUE THREAD

**Issue by sainsb** [agrc/gis.utah.gov#702]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
There are a bunch of invalid features in this shapefile that is a subcomponent of the Lakes/Rivers/Streams dataset...

#### What page is the problem visible
https://gis.utah.gov/data/water/

#### Expected result
I expected: no invalid features

#### Actual result
Instead: invalid features ( 0 area)

![image](https://user-images.githubusercontent.com/1097798/33585830-3bd4530a-d91b-11e7-97ad-87331c6e1ff8.png)

**Comment by steveoh** [comment]
From what I understand, we get the NHD from somewhere and crunch it to try to make it better and more usable for the Utah area. I don't think we have much control over it's accuracy nor are we (AGRC) the data maintainer. We can certainly remove invalid features before publishing the data but it might take some investigating to find out the source issues.

**Comment by ZachBeck** [comment]
UtahMajorRiversPoly has a couple different sources, I'll clean up the remaining sliver polygons

**Comment by stdavis** [comment]
I believed that I removed the features with empty geometries last week from this feature class. I did notice that there were lots of slivers left. I didn't touch those.

**Comment by steveoh** [comment]
> Features with empty geometry were deleted in SGID. However, the data in Drive was not updated. The commit above updates the link to updated data in Drive.
