### ISSUE TITLE
Icon missing on locators page.

### ISSUE THREAD

**Issue by keatonwalker** [agrc/gis.utah.gov#742]
## Issue description
The icon for the Geocoding toolbox is missing.

#### What page is the problem visible
https://gis.utah.gov/data/address-geocoders-locators/#GeocodingToolbox

**Comment by steveoh** [comment]
updated from `fab` to `fas`. That should fix the issue. Thanks for noticing that. 

ps:

fab = font awesome brand, fas = font awesome solid
