### ISSUE TITLE
contents of transit package incorrect 

### ISSUE THREAD

**Issue by gregbunce** [agrc/gis.utah.gov#774]
## Issue description
When you download the 'transit' package you get the contents of the roads and highway package 

#### What page is the problem visible
https://gis.utah.gov/data/transportation/transit/

#### Expected result
To see package contents that pertain to the transit data (ie: bus routes, rail routes, etc.)

**Comment by keatonwalker** [comment]
The transit package now contains the correct bus, commuter and light rail data.

**Comment by steveoh** [comment]
LGTM
