### ISSUE TITLE
click analytics on drive links

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#829]
drive links aren't counted when they are sent directly to drive from an overview page or from the sgid index

### Overview page links

- [ ] SGID10.UTILITIES.ElectricalLines
- [ ] SGID10.SOCIETY.CemeterySurvey
- [ ] SGID10.SOCIETY.FireStations
- [ ] SGID10.SOCIETY.CorrectionalFacilities
- [ ] SGID10.SOCIETY.PublicServiceFacilities1989
- [ ] SGID10.SOCIETY.ShoppingMalls
- [ ] SGID10.SOCIETY.UDOTMap_* (CityLocations, InterestPoints, StateParks)

### SGID Index page links

- [ ] SGID10.UTILITIES.RetailCulinaryWaterServiceAreas
- [ ] SGID10.BOUNDARIES.BLMMonumentsAndNCAs
- [ ] SGID10.BOUNDARIES.BLMMonumentsAndNCAs_Historic
- [ ] SGID10.BOUNDARIES.BLMMonumentsAndNCAs_Line
- [ ] SGID10.BOUNDARIES.Counties_LabelLines
- [ ] SGID10.BOUNDARIES.ForestService
- [ ] SGID10.BOUNDARIES.MetroTownships
- [ ] SGID10.BOUNDARIES.Municipalities_Carto
- [ ] SGID10.BOUNDARIES.Municipalities_Modifications
- [ ] SGID10.BOUNDARIES.UDOTMap_NeighborCounties
- [ ] SGID10.BOUNDARIES.USFSWildernessAreas
- [ ] SGID10.CADASTRE.BLM_RMPTargetedLands
- [ ] SGID10.ECONOMY.TaxAreas2008
- [ ] SGID10.ECONOMY.TaxAreas2009
- [ ] SGID10.ECONOMY.TaxAreas2010 (no link)
- [ ] SGID10.ECONOMY.TaxAreas2011
- [ ] SGID10.ECONOMY.TaxAreas2012
- [ ] SGID10.ECONOMY.TaxAreas2013
- [ ] SGID10.ECONOMY.TaxAreas2014
- [ ] SGID10.ECONOMY.TaxAreas2015
- [ ] SGID10.ECONOMY.TaxAreas2016
- [ ] SGID10.ECONOMY.TaxEntities2008
- [ ] SGID10.ECONOMY.TaxEntities2009
- [ ] SGID10.ECONOMY.TaxEntities2010 (no link)
- [ ] SGID10.ECONOMY.TaxEntities2011
- [ ] SGID10.ECONOMY.TaxEntities2012
- [ ] SGID10.ECONOMY.TaxEntities2013
- [ ] SGID10.ECONOMY.TaxEntities2015
- [ ] SGID10.ECONOMY.TaxEntities2016

**Comment by eneemann** [comment]
List for overview pages can be found here:
https://github.com/agrc/gis.utah.gov/issues/831

List for SGID index page can be found here:
https://github.com/agrc/gis.utah.gov/issues/833

**Comment by eneemann** [comment]
More Overview Page Links:
- SGID10.CLIMATE.NWSForecastZones
- SGID10.CLIMATE.WeatherStations

**Comment by eneemann** [comment]
More SGID Index Page Links:
- SGID10.CADASTRE.LatLongGrid1Degree
- SGID10.DEMOGRAPHIC.MetroMicroStatisticalAreas
- SGID10.DEMOGRAPHIC.UnIncorpAreas2010_Approx
- SGID10.ELEVATION.ContoursGeneralized200Ft

**Comment by steveoh** [comment]
Since we are removing drive links, I'm going to close this since I don't see the point now.
