### ISSUE TITLE
Layer/Aerial Menu Not Visible

### ISSUE THREAD

**Issue by clancyblack** [agrc/gis.utah.gov#839]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
on the crashmapping page the menu to change the aerial is blocked by the filter menus

#### What page is the problem visible
https://crashmapping.utah.gov/

![capture](https://user-images.githubusercontent.com/35848260/39266375-146840e8-4887-11e8-9124-4479c44f85a5.jpg)

#### Expected result
I expected: Consider moving the layer/aerial selection menu to the left side below the zoom in/out buttons.

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
Thanks for the issue report @clancyblack. This issue list is for gis.utah.gov. Next time create the crash app issues in https://github.com/agrc/Crash-web.
