### ISSUE TITLE
Am I able to link my project to an external website?

### ISSUE THREAD

**Issue by weedshop1** [agrc/gis.utah.gov#857]
[Legal Marijuana Online Store](https://www.legalmarijuanaonlinestore.com/) be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
Describe the problem you are having

#### What page is the problem visible
http://gis.utah.gov/

#### Expected result
I expected:

#### Actual result
Instead:

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
Nope
