### ISSUE TITLE
Contours page

### ISSUE THREAD

**Issue by rkelson** [agrc/gis.utah.gov#863]
## Issue description
the 'contours' page can only be found through the top right search OR Related Resources from /Elevation-and-terrain page under Lidar

#### What page is the problem visible
https://gis.utah.gov/data/elevation-and-terrain/contours/

#### Expected result
Make the world a better place
- [x] Add the contours page to the list of data categories (preferred) OR add to the Elevation and Terrain page
- [ ] Add section for these contours: https://gis.utah.gov/dumbing-down-terrain-with-contour-polygons/
- [ ] Add section for other contour Zach has "Bert made him do it"

#### Actual result
Instead:  more "stuff"

**Comment by steveoh** [comment]
@ZachBeck are you waiting on me to do something for this or visa versa?

**Comment by ZachBeck** [comment]
@steveoh I think it should be closed as far as I can tell.
