### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rkelson** [agrc/gis.utah.gov#864]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
this link goes nowhere
![image](https://user-images.githubusercontent.com/6200941/41626199-b79ee196-73d8-11e8-93bb-cc672532a69c.png)

#### What page is the problem visible
https://gis.utah.gov/discover/resources/

#### Expected result
whoever editing this page got the link, hash or whatever correct

#### Actual result
the link goes nowhere

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
@rkelson where would you like this link to go? It went to a page that was merged into this page. Should it link to an anchor tag somewhere?
