### ISSUE TITLE
remove ftp links to utahsgid_vector

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#899]
There are 162 links to ftp://ftp.agrc.utah.gov/UtahSGID_Vector/UTM12_NAD83/. Most of these have been migrated to drive and are most likely not being maintained on the ftp. 

If you already have a list of what is in backseat driver, we should be able to tell what is missing and add what is missing to backseat driver. 

So, let's 

1. add missing data to backseat driver where there are links on the website
1. replace all of the ftp links to utahsgid_vector with backseat driver links
1. remove utahsgid_vector or the duplicated data in that folder on the ftp

**Comment by steveoh** [comment]
@keatonwalker is this something that is still on your list?

**Comment by keatonwalker** [comment]
It can be.

**Comment by steveoh** [comment]
It should

**Comment by steveoh** [comment]
@keatonwalker
