### ISSUE TITLE
Can't download certain elevation tiles

### ISSUE THREAD

**Issue by alexhenrie** [agrc/gis.utah.gov#972]
## Issue description
I can't download the following files:

https://storage.googleapis.com/state-of-utah-sgid-downloads/usgs-3dep-dems/10meter/n42w112_10m.zip
https://storage.googleapis.com/state-of-utah-sgid-downloads/usgs-3dep-dems/10meter/n40w114_10m.zip
https://storage.googleapis.com/state-of-utah-sgid-downloads/usgs-3dep-dems/10meter/n38w114_10m.zip
https://storage.googleapis.com/state-of-utah-sgid-downloads/usgs-3dep-dems/30meter/n40w110_30m.zip

#### What page is the problem visible on
https://raster.utah.gov/?cat=10%20Meter%20%7BDEM%7D
https://raster.utah.gov/?cat=30%20Meter%20%7BDEM%7D

#### Expected result
I expected: The files to download.

#### Actual result
Instead: The download hangs forever.

**Comment by steveoh** [comment]
Thanks we will take a look and keep you updated here.

**Comment by alexhenrie** [comment]
It looks like it was a temporary problem. I was able to successfully download the files today.

**Comment by steveoh** [comment]
Great sorry about the cloud hiccup
