### ISSUE TITLE
SGID.ENERGY.DNROilGasUnits

### ISSUE THREAD

**Issue by nathankota** [agrc/gis.utah.gov#981]
UDOGM will discontinue updating SGID10.ENERGY.DNROilGasUnits. The source data are actually from the BLM, and provided by 
https://gis.blm.gov/utarcgis/rest/services/Energy/BLM_UT_min_OGUnitAgreements_MapService/MapServer/0

UDOGM think it is still an important layer to maintain in the SGID. Need to rename the layer to indicate its source (perhaps SGID10.ENERGY.BLMOilGasUnits), and have forklift update from the BLM map service.

**Comment by stdavis** [comment]
I transferred this to the gis.utah.gov repo since forklift does not update that layer in SGID. I'll open a PR to update the web page.

**Comment by steveoh** [comment]
The sgid index will need to be updated from the stewardship spreadsheet as well...

**Comment by stdavis** [comment]
OK. Web page and SGID Index is updated. ✅

Should we ask @ZachBeck to remove this dataset from the SGID SDE database?

**Comment by steveoh** [comment]
I believe it is used in pallets? We should check...

**Comment by ZachBeck** [comment]
To me it doesn't make sense to have links to data all over the place and not a central repository.

**Comment by stdavis** [comment]
> I believe it is used in pallets? We should check...

I checked and couldn't find it in any pallets.

**Comment by steveoh** [comment]
Should this stay open?

**Comment by stdavis** [comment]
I'm fine with it closing. Someone just needs to make the decision about what to do with the feature class in SGID. Since we no longer have a great way to update it, I wonder if it should be removed.

**Comment by nathankota** [comment]
Link to BLM data was provided on website, and the layer was removed from the sde, both of which were requested by DOGM. This can be closed.
